export type PriceStrategy = "quick" | "market" | "premium";
export interface UpgradeLevelDefinition { cost:number; value:number }
export interface UpgradeDefinition { id:string; name:string; category:string; effectType:string; levels:readonly UpgradeLevelDefinition[]; prerequisites:readonly string[]; foundationProvided?:boolean }
const u=(id:string,name:string,category:string,effectType:string,costs:number[],values:number[],prerequisites:string[]=[],foundationProvided=false):UpgradeDefinition=>({id,name,category,effectType,levels:costs.map((cost,i)=>({cost,value:values[i]})),prerequisites,foundationProvided});
export const UPGRADES:readonly UpgradeDefinition[]=[u("display-slot-2","Display Slot II","display","display-capacity",[60],[2]),u("display-slot-3","Display Slot III","display","display-capacity",[250],[3],["display-slot-2"]),u("display-slot-4","Display Slot IV","display","display-capacity",[800],[4],["display-slot-3"]),u("contract-queue-1","Contract Queue I","display","queue-capacity",[180],[1],["display-slot-2"]),u("contract-queue-2","Contract Queue II","display","queue-capacity",[600],[2],["contract-queue-1"]),u("saved-price-presets","Saved Price Presets","display","price-presets",[100],[1]),u("multi-unit-display","Multi-Unit Display","display","multi-unit",[1500],[1],["display-slot-4","contract-queue-2","saved-price-presets"]),u("proofing-schedule","Proofing Schedule","business","dough-windows",[200,700,2000,5000,12000],[2,3,4,5,6]),u("wider-audience","Wider Audience","market","recovery-speed",[180,500,1400],[.1,.2,.35]),u("customer-loyalty","Customer Loyalty","market","demand-ceiling",[250,750,2000],[5,10,15]),u("brand-resilience","Brand Resilience","market","sale-impact",[300,900,2400],[.1,.2,.3]),u("premium-packaging","Premium Packaging","market","neutral-value",[500,1500,4000],[.03,.06,.1]),u("advertising-efficiency","Advertising Efficiency","market","advertising-discount",[400,1200,3000],[.1,.2,.3]),u("bulk-supplier-account","Bulk Supplier Account","suppliers","bulk-pack",[600],[.1]),u("common-ingredient-discount","Common Ingredient Discount","suppliers","common-discount",[250,700,1800],[.05,.1,.15]),u("filling-ingredient-discount","Filling Ingredient Discount","suppliers","filling-discount",[400,1100,2800],[.05,.1,.15]),u("premium-ingredient-discount","Premium Ingredient Discount","suppliers","premium-discount",[800,2200,5500],[.05,.1,.15]),u("pantry-sorting","Pantry Sorting","pantry","sorting",[40],[1]),u("low-stock-markers","Low-Stock Markers","pantry","low-stock",[80],[1],["pantry-sorting"]),u("recipe-use-preview","Recipe Use Preview","pantry","recipe-use",[120],[1],["pantry-sorting"]),u("craftable-filter","Craftable Filter","kitchen","craftable-filter",[40],[1]),u("favourite-recipes","Favourite Recipes","kitchen","favourites",[50],[1]),u("ingredient-preview","Ingredient Preview","kitchen","ingredient-preview",[120],[1]),u("planned-batch","Planned Batch","kitchen","planned-batch",[250],[1],["ingredient-preview","multi-craft"]),u("multi-craft","Multi-Craft","kitchen","multi-craft",[],[],[],true),u("recipe-categories","Recipe Categories","kitchen","categories",[],[],[],true)];
export const MARKET_INFORMATION_UPGRADES:readonly UpgradeDefinition[]=[u("price-ledger","Price Ledger","information","rounded-price-observations",[40],[400]),u("trend-indicator","Trend Indicator","information","market-trend",[120],[.75],["price-ledger"]),u("market-history","Market History","information","price-history",[300],[1],["price-ledger"]),u("market-research","Market Research","information","boundary-proximity",[600],[.1],["trend-indicator","market-history"]),u("sales-analytics","Sales Analytics","information","product-statistics",[900],[1],["market-history"])];
export const ALL_UPGRADES:readonly UpgradeDefinition[]=[...MARKET_INFORMATION_UPGRADES,...UPGRADES];
export interface AdvertisingDefinition { id:string; name:string; baseCost:number; targetType:"product"|"all-products"|"neglected-products"; effectType:string; effectValue:number; durationMs?:number }
export const ADVERTISING:readonly AdvertisingDefinition[]=[{id:"local-flyers",name:"Local Flyers",baseCost:15,targetType:"product",effectType:"demand-boost",effectValue:8},{id:"social-campaign",name:"Social Campaign",baseCost:75,targetType:"all-products",effectType:"demand-boost",effectValue:4},{id:"variety-campaign",name:"Variety Campaign",baseCost:100,targetType:"neglected-products",effectType:"demand-boost",effectValue:10},{id:"grand-reopening",name:"Grand Reopening",baseCost:300,targetType:"all-products",effectType:"demand-boost",effectValue:12},{id:"product-spotlight",name:"Product Spotlight",baseCost:40,targetType:"product",effectType:"spotlight",effectValue:1},{id:"window-promotion",name:"Window Promotion",baseCost:60,targetType:"product",effectType:"target-growth",effectValue:1.5,durationMs:86400000},{id:"bakery-promotion",name:"Bakery Promotion",baseCost:150,targetType:"all-products",effectType:"recovery",effectValue:1.35,durationMs:86400000}];
export const upgradeById=(id:string)=>ALL_UPGRADES.find(x=>x.id===id); export const campaignById=(id:string)=>ADVERTISING.find(x=>x.id===id);
export const ownedLevel=(items:readonly {upgradeId:string;level:number}[],id:string)=>items.filter(x=>x.upgradeId===id).reduce((n,x)=>Math.max(n,x.level),0);
export const effectValue=(items:readonly {upgradeId:string;level:number}[],id:string)=>{const d=upgradeById(id),l=ownedLevel(items,id);return l&&d?d.levels[l-1]?.value??0:0};
