import { AppData, BakeryLedgerEntry, BakeryState, MarketPriceObservation, MilestoneCompletion, ProductSalesStatistics, newId } from "../domain";
import { PRODUCTS, RECIPES, SUPPLIERS } from "./bakeryCatalogue";
import { deriveEffectiveMarketModifiers, deriveProductMarket, marketConfigFor, marketPriceForDemand } from "./bakeryMarket";

export const BAKERY_BALANCE_DATA_VERSION=1;
export const BAKERY_SIMULATION_VERSION="1.1.0";
export const MARKET_OBSERVATION_LIMIT=400;
export const TREND_STABILITY_THRESHOLD=.75;
export const MARKET_BOUNDARY_NEAR_RATIO=.1;
const hasUpgrade=(b:BakeryState,id:string)=>b.foundationCapabilities.includes(id)||b.purchasedUpgrades.some(x=>x.upgradeId===id&&x.level>0);

export interface BakeryMilestoneDefinition { id:string;title:string;description:string;conditionType:string;threshold?:number;rewardCoin:number;prerequisiteIds?:string[];artKey?:string }
export const MILESTONES:readonly BakeryMilestoneDefinition[]=[
 {id:"first-donut",title:"First Donut",description:"Bake the first Donut",conditionType:"baked",threshold:1,rewardCoin:1},
 {id:"first-sale",title:"First Sale",description:"Complete the first sale",conditionType:"sales",threshold:1,rewardCoin:2},
 {id:"first-new-recipe",title:"First New Recipe",description:"Purchase the first non-starting recipe",conditionType:"recipes",threshold:3,rewardCoin:3},
 {id:"first-ingredient-pack",title:"First Ingredient Pack",description:"Purchase the first ingredient pack",conditionType:"ingredient-pack",threshold:1,rewardCoin:5},
 {id:"ten-sales",title:"Ten Sales",description:"Complete 10 sales",conditionType:"sales",threshold:10,rewardCoin:10,prerequisiteIds:["first-sale"]},
 {id:"five-products",title:"Five Products",description:"Sell five distinct products",conditionType:"distinct-products",threshold:5,rewardCoin:20,prerequisiteIds:["first-sale"]},
 {id:"ten-recipes",title:"Ten Recipes",description:"Own 10 recipes",conditionType:"recipes",threshold:10,rewardCoin:40},
 {id:"first-premium-sale",title:"First Premium Sale",description:"Sell any Premium Combination product",conditionType:"premium-sale",threshold:1,rewardCoin:25},
 {id:"one-hundred-coin",title:"One Hundred Coin",description:"Earn 100 lifetime Coin from sales",conditionType:"sale-revenue",threshold:100,rewardCoin:10},
 {id:"one-thousand-coin",title:"One Thousand Coin",description:"Earn 1,000 lifetime Coin from sales",conditionType:"sale-revenue",threshold:1000,rewardCoin:50,prerequisiteIds:["one-hundred-coin"]},
 {id:"ten-thousand-coin",title:"Ten Thousand Coin",description:"Earn 10,000 lifetime Coin from sales",conditionType:"sale-revenue",threshold:10000,rewardCoin:250,prerequisiteIds:["one-thousand-coin"]},
 {id:"second-display",title:"Second Display",description:"Unlock Display Slot II",conditionType:"upgrade",threshold:1,rewardCoin:20},
 {id:"all-suppliers",title:"All Suppliers",description:"Unlock every paid supplier tier",conditionType:"suppliers",threshold:SUPPLIERS.length-1,rewardCoin:150},
 {id:"all-core-recipes",title:"All Core Recipes",description:"Unlock every core recipe",conditionType:"recipes",threshold:RECIPES.length,rewardCoin:300},
 {id:"complete-catalogue",title:"Complete Catalogue",description:"Sell every core product at least once",conditionType:"catalogue",threshold:PRODUCTS.length,rewardCoin:500,prerequisiteIds:["all-core-recipes"]}
];

export const emptyProductSalesStatistics=():ProductSalesStatistics=>({lifetimeUnitsBaked:0,lifetimeUnitsSold:0,lifetimeCoinRevenue:0,completedSalePriceTotal:0,marketPriceAtListingTotal:0,completedSaleDurationTotalMs:0,highestCompletedSalePrice:null,fastestCompletedNonImmediateSaleMs:null,longestCompletedSaleMs:null,lastSaleAt:null,belowMarketSales:0,atMarketSales:0,aboveMarketSales:0});
export function bakeryReputation(b:BakeryState){return b.statistics.totalDonutsSold+5*Object.values(b.statistics.soldByProduct).filter(n=>n>0).length+10*b.unlockedRecipeIds.length+15*b.unlockedSupplierIds.length+25*b.completedMilestones.length}
export function reputationTitle(value:number){return value>=800?"Landmark Bakery":value>=400?"Destination Bakery":value>=175?"Established Bakery":value>=75?"Local Favourite":value>=25?"Neighbourhood Baker":"Home Baker"}
export function milestoneProgress(b:BakeryState,d:BakeryMilestoneDefinition){switch(d.conditionType){case"baked":return b.statistics.totalDonutsCrafted;case"sales":return b.statistics.totalDonutsSold;case"recipes":return b.unlockedRecipeIds.length;case"ingredient-pack":return b.resourceTransactions.filter(x=>x.type==="ingredient-purchased"&&x.itemId==="coin").length;case"distinct-products":return Object.values(b.statistics.soldByProduct).filter(n=>n>0).length;case"premium-sale":return PRODUCTS.filter(x=>x.marketTier==="combination").some(x=>(b.statistics.soldByProduct[x.id]??0)>0)?1:0;case"sale-revenue":return b.statistics.lifetimeCoinEarned;case"upgrade":return hasUpgrade(b,"display-slot-2")?1:0;case"suppliers":return b.unlockedSupplierIds.length;case"catalogue":return PRODUCTS.filter(x=>(b.statistics.soldByProduct[x.id]??0)>0).length;default:return 0}}
export function evaluateMilestones(data:AppData,operationId:string,at=new Date(),compatibilityAward=false):AppData{let b=data.bakery;for(const d of MILESTONES){if(b.completedMilestones.some(x=>x.milestoneId===d.id))continue;if(d.prerequisiteIds?.some(id=>!b.completedMilestones.some(x=>x.milestoneId===id)))continue;if(milestoneProgress(b,d)<(d.threshold??1))continue;const key=`milestone:${d.id}`,tx:BakeryLedgerEntry={id:newId("bakery_tx"),operationId,type:"milestone-reward",itemId:"coin",amount:d.rewardCoin,source:d.id,timestamp:at.toISOString(),idempotencyKey:key};const completion:MilestoneCompletion={milestoneId:d.id,completedAt:at.toISOString(),idempotencyKey:key,rewardTransactionId:tx.id,compatibilityAward};b={...b,balances:{...b.balances,coin:b.balances.coin+d.rewardCoin},rewardLedger:[...b.rewardLedger,tx],resourceTransactions:[...b.resourceTransactions,tx],completedMilestones:[...b.completedMilestones,completion]}}return b===data.bakery?data:{...data,bakery:b}}

export function observeMarketPrices(b:BakeryState,at:Date,reason:MarketPriceObservation["reason"],forceDaily=false){if(!hasUpgrade(b,"price-ledger"))return b;let observations=[...b.marketPriceObservations];const context={modifiers:deriveEffectiveMarketModifiers(b),timedCampaigns:b.activeCampaigns};for(const productId of b.unlockedRecipeIds){const market=b.productMarkets.find(x=>x.productId===productId);if(!market)continue;const price=deriveProductMarket(market,at,context).marketPrice,latest=[...observations].filter(x=>x.productId===productId).sort((a,c)=>a.observedAt.localeCompare(c.observedAt)).at(-1);const localDay=new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Sydney",year:"numeric",month:"2-digit",day:"2-digit"}).format(at);const latestDay=latest?new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Sydney",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(latest.observedAt)):"";if(latest?.roundedMarketPrice===price&&(!forceDaily||latestDay===localDay))continue;observations.push({id:newId("market_obs"),productId,observedAt:at.toISOString(),roundedMarketPrice:price,reason});const product=observations.filter(x=>x.productId===productId).sort((a,c)=>a.observedAt.localeCompare(c.observedAt));if(product.length>MARKET_OBSERVATION_LIMIT){const remove=new Set(product.slice(0,product.length-MARKET_OBSERVATION_LIMIT).map(x=>x.id));observations=observations.filter(x=>!remove.has(x.id))}}return {...b,marketPriceObservations:observations.sort((a,c)=>a.observedAt.localeCompare(c.observedAt))}}
export function marketTrend(b:BakeryState,productId:string,at=new Date()):"Rising"|"Stable"|"Falling"{const state=b.productMarkets.find(x=>x.productId===productId);if(!state)return"Stable";const context={modifiers:deriveEffectiveMarketModifiers(b),timedCampaigns:b.activeCampaigns},current=deriveProductMarket(state,at,context).state,projected=deriveProductMarket(current,new Date(at.getTime()+86400000),context).state,diff=projected.demand-current.demand;return Math.abs(diff)<TREND_STABILITY_THRESHOLD?"Stable":diff>0?"Rising":"Falling"}
export function marketProximity(b:BakeryState,productId:string,at=new Date()){const state=b.productMarkets.find(x=>x.productId===productId),config=marketConfigFor(productId);if(!state||!config)return"At current market limit";const modifiers=deriveEffectiveMarketModifiers(b),context={modifiers,timedCampaigns:b.activeCampaigns},demand=deriveProductMarket(state,at,context).state.demand,current=marketPriceForDemand(config,demand,modifiers);let up:number|undefined,down:number|undefined;for(let n=config.minimumDemand;n<=config.maximumDemand;n+=.01){const p=marketPriceForDemand(config,n,modifiers);if(p>=current+1&&up===undefined)up=n;if(p<=current-1)down=n}const band=(config.maximumDemand-config.minimumDemand)/Math.max(1,marketPriceForDemand(config,config.maximumDemand,modifiers)-marketPriceForDemand(config,config.minimumDemand,modifiers));const upDistance=up===undefined?Infinity:up-demand,downDistance=down===undefined?Infinity:demand-down;if(!Number.isFinite(upDistance)&&!Number.isFinite(downDistance))return"At current market limit";if(Math.min(upDistance,downDistance)<=band*MARKET_BOUNDARY_NEAR_RATIO){if(upDistance===downDistance)return marketTrend(b,productId,at)==="Falling"?"Near a lower price":"Near a higher price";return upDistance<downDistance?"Near a higher price":"Near a lower price"}return"Comfortably within current price"}
