import { describe, expect, it } from "vitest";
import { createSeedData } from "../../seed";
import { createInitialBakeryState, migrateAppData } from "../../domain";
import { applyProjectCompletionReward, applyTaskCompletionRewards, craft, instantPrice, listProduct, maximumAskingPrice, purchaseIngredient, purchaseRecipe, removeContract, resolveDueContracts, saleDurationMs, validateBakeryConfiguration } from "./bakeryDomain";

const funded = () => { const data=createSeedData(); data.bakery.balances={...data.bakery.balances,coin:100,dough:20,sprinkles:100,icing:20,sugar:20,cinnamon:20}; return data; };
describe("Bakery vertical slice",()=>{
  it("migrates existing snapshots prospectively and idempotently",()=>{const at=new Date("2026-07-01T00:00:00Z");const raw={...createSeedData(),bakery:undefined};const once=migrateAppData(raw,at);expect(once.bakery).toEqual(createInitialBakeryState(at));expect(migrateAppData(once,at).bakery).toEqual(once.bakery);expect(once.bakery.rewardLedger).toHaveLength(0)});
  it("awards first daily Dough and task Sprinkles idempotently",()=>{const data=createSeedData();const task=data.tasks[0];const now=new Date("2026-07-01T02:00:00Z");let next=applyTaskCompletionRewards(data,data,task,"op1",now);expect(next.bakery.balances.dough).toBe(1);expect(next.bakery.balances.sprinkles).toBe(2);next=applyTaskCompletionRewards(next,next,task,"op2",now);expect(next.bakery.balances).toMatchObject({dough:1,sprinkles:2})});
  it("awards overdue Sprinkles, aggregate and project Icing",()=>{let data=createSeedData();const task={...data.tasks[0],scheduledDate:"2020-01-01"};data=applyTaskCompletionRewards(data,data,task,"a",new Date("2026-07-01T02:00:00Z"));expect(data.bakery.balances.sprinkles).toBe(1);data=applyTaskCompletionRewards(data,data,{...task,id:"agg",aggregate:true},"b");data=applyProjectCompletionReward(data,"p","c");expect(data.bakery.balances.icing).toBe(7)});
  it("purchases packs and reveals cinnamon recipe atomically",()=>{let data=funded();data=purchaseIngredient(data,"sugar");expect(data.bakery.balances).toMatchObject({coin:95,sugar:30});expect(data.bakery.revealedRecipeIds).toContain("cinnamon-sugar-donut");data=purchaseIngredient(data,"cinnamon");expect(data.bakery.balances).toMatchObject({coin:75,cinnamon:30})});
  it("purchases and crafts data-driven recipes without negative stock",()=>{let data=funded();data=purchaseRecipe(data,"iced-sprinkle-donut");expect(data.bakery.balances.coin).toBe(100);data=craft(data,"iced-sprinkle-donut",2);expect(data.bakery.finishedProducts["iced-sprinkle-donut"]).toBe(2);expect(data.bakery.balances).toMatchObject({dough:18,sprinkles:92,icing:18});expect(()=>craft(data,"iced-sprinkle-donut",100)).toThrow()});
  it("uses the specified deterministic duration curve and cap",()=>{expect(instantPrice(3)).toBe(1);expect(saleDurationMs(3,1)).toBe(0);expect(saleDurationMs(3,3)/3600000).toBe(8);expect(saleDurationMs(3,5)/3600000).toBe(32);expect(saleDurationMs(3,maximumAskingPrice(3))).toBeLessThanOrEqual(72*3600000);expect(saleDurationMs(3,maximumAskingPrice(3)+1)).toBeGreaterThan(72*3600000)});
  it("locks, removes, and idempotently resolves contracts",()=>{let data=funded();data.bakery.finishedProducts["sprinkle-donut"]=2;const now=new Date("2026-07-01T00:00:00Z");let listed=listProduct(data,"sprinkle-donut",3,now);const contract=listed.bakery.activeContracts[0];expect(contract).toMatchObject({askingPrice:3,marketPrice:3,durationMs:8*3600000});let removed=removeContract(listed,contract.id);expect(removed.bakery.finishedProducts["sprinkle-donut"]).toBe(2);expect(removed.bakery.balances.coin).toBe(100);listed=listProduct(removed,"sprinkle-donut",1,now);let sold=resolveDueContracts(listed,now);expect(sold.bakery.balances.coin).toBe(103);expect(resolveDueContracts(sold,now).bakery.balances.coin).toBe(103)});
  it("validates the initial economy configuration",()=>expect(validateBakeryConfiguration()).toMatchObject({valid:true,weakMarketProfitabilityReady:true,lineageValuePreserved:true}));
});
