import { describe,expect,it } from "vitest";
import { createInitialBakeryState, normaliseBakeryState } from "../../domain";
import { marketConfigFor, marketPriceForDemand } from "../../domain/bakeryMarket";
import { bakeryArtKeys, expectedBakeryArtPath, missingBakeryArtCount } from "./artRegistry";
import { ingredientEntriesInPurchaseOrder, ingredientIdsInPurchaseOrder, INGREDIENTS, INGREDIENT_BY_ID, INGREDIENT_IDS_IN_PURCHASE_ORDER, PRODUCTS, PRODUCT_BY_ID, RECIPES, RECIPE_BY_ID, RECIPE_CATEGORIES, SUPPLIERS, discoverableRecipeIds } from "../../domain/bakeryCatalogue";
import { createSeedData } from "../../seed";
import { craft, listProduct, maxCraftable, purchaseIngredient,purchaseRecipe,purchaseSupplier,resolveDueContracts,validateBakeryConfiguration } from "./bakeryDomain";
const T0=new Date("2026-07-01T00:00:00Z");
const funded=()=>{const data=createSeedData();data.bakery=createInitialBakeryState(T0);data.bakery.balances={...data.bakery.balances,coin:10000,dough:20,sprinkles:100,icing:20,sugar:20,cinnamon:20,cocoa:20,vanilla:20,chocolate:20,jam:20,custard:20,cream:20,coconut:20,caramel:20,"lemon-curd":20,"apple-filling":20,coffee:20,"maple-syrup":20,"biscuit-crumb":20,"peanut-butter":20,hazelnut:20,berries:20};return data};
const newRecipes=[
  {id:"caramel-coconut-donut",name:"Caramel Coconut Donut",ingredients:{dough:1,icing:1,caramel:1,coconut:1},inputCost:23,neutral:138,weak:90,price:580,prerequisites:["caramel-glazed-donut","coconut-iced-donut"],lineage:[["coconut-iced-donut",11,92],["caramel-glazed-donut",12,72]]},
  {id:"maple-apple-donut",name:"Maple Apple Donut",ingredients:{dough:1,sugar:1,cinnamon:1,"apple-filling":1,"maple-syrup":1},inputCost:31,neutral:154,weak:100,price:640,prerequisites:["apple-cinnamon-donut","maple-glazed-donut"],lineage:[["apple-cinnamon-donut",15,72],["maple-glazed-donut",15,76]]},
  {id:"peanut-butter-biscuit-donut",name:"Peanut Butter Biscuit Donut",ingredients:{dough:1,sugar:1,icing:1,"peanut-butter":1,"biscuit-crumb":1},inputCost:34,neutral:180,weak:117,price:780,prerequisites:["peanut-butter-chocolate-donut","cookies-and-cream-donut"],lineage:[["cookies-and-cream-donut",7,8],["peanut-butter-chocolate-donut",11,30]]},
  {id:"vanilla-berry-cream-donut",name:"Vanilla Berry Cream Donut",ingredients:{dough:1,sugar:1,icing:1,vanilla:1,cream:1,berries:1},inputCost:34,neutral:198,weak:129,price:850,prerequisites:["vanilla-glazed-donut","berry-cream-donut"],lineage:[["berry-cream-donut",4,18],["vanilla-glazed-donut",29,168]]},
  {id:"hazelnut-coffee-cream-donut",name:"Hazelnut Coffee Cream Donut",ingredients:{dough:1,sugar:1,cream:1,coffee:1,hazelnut:1},inputCost:43,neutral:204,weak:133,price:880,prerequisites:["hazelnut-chocolate-donut","coffee-cream-donut"],lineage:[["coffee-cream-donut",18,106],["hazelnut-chocolate-donut",19,46]]},
] as const;
const inputCost=(ingredients:Record<string,number>)=>Object.entries(ingredients).reduce((sum,[id,amount])=>sum+((INGREDIENT_BY_ID[id]?.packPrice??0)/(INGREDIENT_BY_ID[id]?.packQuantity??1))*amount,0);
const expansionValues=[
 ["sugar-donut",0,6],["cinnamon-iced-donut",75,30],["vanilla-sprinkle-donut",110,40],["chocolate-sprinkle-donut",135,46],["chocolate-vanilla-donut",180,58],["lemon-glazed-donut",220,66],["vanilla-custard-donut",230,72],["chocolate-cream-donut",320,90],["vanilla-cream-donut",380,96],["cinnamon-cream-donut",390,98],["chocolate-caramel-donut",400,104],["chocolate-coconut-donut",420,108],["jam-custard-donut",440,112],["caramel-custard-donut",460,116],["chocolate-biscuit-donut",500,122],["peanut-butter-and-jam-donut",520,126],["berry-jam-donut",540,130],["berry-custard-donut",560,132],["vanilla-hazelnut-donut",620,146],["hazelnut-cream-donut",650,152],["lemon-berry-donut",680,158],["apple-crumble-donut",760,176],["vanilla-latte-donut",800,184],["chocolate-vanilla-cream-donut",880,196],["vanilla-berry-custard-donut",900,202],["lamington-donut",930,208],["caramel-latte-donut",960,214],["chocolate-hazelnut-cream-donut",1250,250],["chocolate-caramel-biscuit-donut",1350,260],["neapolitan-donut",1650,285],["black-forest-donut",2200,320],["ultimate-apple-maple-crumble-donut",2500,340],
] as const;
describe("Bakery core catalogue",()=>{
 it("registers every expected Bakery interface and gameplay asset path",()=>{expect(bakeryArtKeys).toHaveLength(116);expect(new Set(bakeryArtKeys).size).toBe(116);expect(expectedBakeryArtPath("currencies")).toBe("../../assets/bakery/interface/currencies.png");expect(expectedBakeryArtPath("bakery-pantry")).toBe("../../assets/bakery/navigation/bakery-pantry.png");expect(expectedBakeryArtPath("supplier-crate-common")).toBe("../../assets/bakery/business/supplier-crate-common.png");expect(expectedBakeryArtPath("coin")).toBe("../../assets/bakery/currencies/coin.png");expect(expectedBakeryArtPath("apple-filling")).toBe("../../assets/bakery/ingredients/apple-filling.png");expect(expectedBakeryArtPath("sprinkle-donut")).toBe("../../assets/bakery/products/sprinkle-donut.png");expect(missingBakeryArtCount()).toBe(32);});
 it("contains all configured content and passes economic validation",()=>{expect(INGREDIENTS).toHaveLength(26);expect(SUPPLIERS).toHaveLength(5);expect(RECIPES).toHaveLength(100);expect(PRODUCTS).toHaveLength(100);expect(new Set(RECIPES.map(x=>x.id)).size).toBe(100);expect(new Set(PRODUCTS.map(x=>x.id)).size).toBe(100);expect(new Set(RECIPES.map(x=>x.category))).toEqual(new Set(RECIPE_CATEGORIES));expect(validateBakeryConfiguration()).toMatchObject({valid:true,weakMarketProfitabilityReady:true,lineageValuePreserved:true});for(const ingredient of INGREDIENTS){expect(ingredient.packQuantity).toBe(10);expect(ingredient.packPrice/ingredient.packQuantity).toBeGreaterThan(0)}});
 it("uses supplier progression as the one ingredient display order",()=>{expect(INGREDIENT_IDS_IN_PURCHASE_ORDER).toEqual(SUPPLIERS.flatMap((supplier)=>supplier.ingredientIds));expect(ingredientIdsInPurchaseOrder(["berries","sugar","mint","dough","cocoa","cream"])).toEqual(["dough","sugar","cocoa","cream","mint","berries"]);expect(ingredientEntriesInPurchaseOrder({berries:1,dough:2,cream:3,sugar:4})).toEqual([["dough",2],["sugar",4],["cream",3],["berries",1]]);});
 it("registers the five Premium Combination recipes, products, markets, and art keys",()=>{for(const expected of newRecipes){const recipe=RECIPE_BY_ID[expected.id],product=PRODUCT_BY_ID[expected.id],market=marketConfigFor(expected.id);expect(recipe).toMatchObject({id:expected.id,productId:expected.id,name:expected.name,category:"Premium Combination",price:expected.price,ingredients:expected.ingredients,yield:1});expect(product).toMatchObject({id:expected.id,name:expected.name,neutralPrice:expected.neutral,marketTier:"combination",assetKey:expected.id});expect(market).toMatchObject({productId:expected.id,neutralDemand:50,minimumDemand:0,maximumDemand:100,unmetDemandCeiling:78,recoveryHalfLifeHours:24,unmetDemandHalfLifeHours:96,completedSaleImpact:6});expect(bakeryArtKeys).toContain(expected.id);expect(missingBakeryArtCount()).toBe(32);}});
 it("uses the exact new recipe ingredient formulas and economic values",()=>{for(const expected of newRecipes){const recipe=RECIPE_BY_ID[expected.id];const product=PRODUCT_BY_ID[expected.id];expect(recipe.ingredients).toEqual(expected.ingredients);expect(inputCost(recipe.ingredients)).toBe(expected.inputCost);expect(product.neutralPrice).toBe(expected.neutral);expect(marketPriceForDemand(marketConfigFor(expected.id)!,0)).toBe(expected.weak);expect(product.neutralPrice).toBeGreaterThan(expected.inputCost);expect(expected.weak).toBeGreaterThan(expected.inputCost);for(const [parent,addedCost,increase] of expected.lineage){expect(PRODUCT_BY_ID[expected.id].neutralPrice-PRODUCT_BY_ID[parent].neutralPrice).toBe(increase);expect(increase).toBeGreaterThan(addedCost);}}});
 it("uses every purchased ingredient in at least two recipes",()=>{const counts=Object.fromEntries(INGREDIENTS.map((ingredient)=>[ingredient.id,RECIPES.filter((recipe)=>recipe.ingredients[ingredient.id]>0).length]));expect(counts).toMatchObject({vanilla:11,coconut:4,caramel:6,"apple-filling":4,"maple-syrup":3,"biscuit-crumb":6,"peanut-butter":3,hazelnut:5,berries:7});for(const ingredient of INGREDIENTS)expect(counts[ingredient.id]).toBeGreaterThanOrEqual(2);});
 it("enforces supplier progression and discovers from durable purchase history",()=>{let data=funded();expect(()=>purchaseSupplier(data,"filling-supplier","bad",T0)).toThrow(/prerequisite/i);data=purchaseSupplier(data,"common-supplier","common",T0);expect(data.bakery.unlockedSupplierIds).toContain("common-supplier");data=purchaseIngredient(data,"cocoa","cocoa",T0);expect(data.bakery.revealedRecipeIds).toContain("cocoa-sugar-donut");data.bakery.balances.cocoa=0;expect(data.bakery.revealedRecipeIds).toContain("cocoa-sugar-donut")});
 it("discovers each new recipe only after both prerequisite recipes are owned",()=>{for(const expected of newRecipes){const [first,second]=expected.prerequisites;expect(discoverableRecipeIds([],[],[first])).not.toContain(expected.id);expect(discoverableRecipeIds([],[],[second])).not.toContain(expected.id);expect(discoverableRecipeIds([],[],[first,second])).toContain(expected.id);const existing=normaliseBakeryState({...createInitialBakeryState(T0),unlockedRecipeIds:["sprinkle-donut",first,second],revealedRecipeIds:["sprinkle-donut","iced-sprinkle-donut"]},T0);expect(existing.revealedRecipeIds).toContain(expected.id);expect(existing.unlockedRecipeIds).not.toContain(expected.id);const again=normaliseBakeryState(existing,T0);expect(again.revealedRecipeIds.filter(id=>id===expected.id)).toHaveLength(1);}});
 it("purchases, creates neutral market state, crafts, lists, and sells each new product generically",()=>{for(const expected of newRecipes){let data=funded();data.bakery.revealedRecipeIds=[...data.bakery.revealedRecipeIds,expected.id];const spentBefore=data.bakery.statistics.coinSpentOnRecipes;data=purchaseRecipe(data,expected.id,`buy-${expected.id}`,T0);expect(data.bakery.statistics.coinSpentOnRecipes).toBe(spentBefore+expected.price);expect(data.bakery.productMarkets.filter(x=>x.productId===expected.id)).toHaveLength(1);expect(data.bakery.productMarkets.find(x=>x.productId===expected.id)).toMatchObject({demand:50,unlockedAt:T0.toISOString(),lastCalculatedAt:T0.toISOString()});expect(purchaseRecipe(data,expected.id,`retry-${expected.id}`,T0)).toBe(data);expect(maxCraftable(data,expected.id)).toBe(20);data=craft(data,expected.id,2,`craft-${expected.id}`,T0);expect(data.bakery.finishedProducts[expected.id]).toBe(2);for(const [id,amount] of Object.entries(expected.ingredients))expect(data.bakery.balances[id]).toBe(20-amount*2);data=listProduct(data,expected.id,expected.neutral,T0,`list-${expected.id}`);expect(data.bakery.activeContracts[0]).toMatchObject({productId:expected.id,askingPrice:expected.neutral,marketPrice:expected.neutral,demandAtListing:50});data=resolveDueContracts(data,new Date(T0.getTime()+8*3600000),`sell-${expected.id}`);expect(data.bakery.statistics.soldByProduct[expected.id]).toBe(1);expect(data.bakery.statistics.coinByProduct[expected.id]).toBe(expected.neutral);}});
 it("creates one market at recipe purchase time",()=>{let data=funded();data=purchaseRecipe(data,"iced-sprinkle-donut","recipe",T0);expect(data.bakery.productMarkets.filter(m=>m.productId==="iced-sprinkle-donut")).toHaveLength(1);expect(purchaseRecipe(data,"iced-sprinkle-donut","retry",T0)).toBe(data)});
 it("registers and crafts every catalogue-data version 4 recipe",()=>{for(const [id,cost,neutral] of expansionValues){const recipe=RECIPE_BY_ID[id],product=PRODUCT_BY_ID[id],market=marketConfigFor(id)!;expect(recipe).toMatchObject({id,productId:id,price:cost,yield:1,assetKey:id});expect(recipe.ingredients.dough).toBe(1);expect(product).toMatchObject({id,neutralPrice:neutral,assetKey:id});expect(market).toMatchObject({neutralDemand:50,minimumDemand:0,maximumDemand:100});expect(bakeryArtKeys).toContain(id);let data=funded();data.bakery.unlockedRecipeIds=[...data.bakery.unlockedRecipeIds,id];data.bakery.productMarkets=[...data.bakery.productMarkets,...(data.bakery.productMarkets.some(x=>x.productId===id)?[]:[{productId:id,demand:50,unlockedAt:T0.toISOString(),lastCalculatedAt:T0.toISOString()}])];const before={...data.bakery.balances};data=craft(data,id,2,`craft-${id}`,T0);expect(data.bakery.finishedProducts[id]).toBe(2);for(const [ingredient,amount] of Object.entries(recipe.ingredients))expect(data.bakery.balances[ingredient]).toBe(before[ingredient]-amount*2)}});
 it("migrates Sugar Donut without grants, cost, history, or retroactive demand",()=>{const legacy=createInitialBakeryState(T0);legacy.unlockedRecipeIds=["sprinkle-donut"];legacy.revealedRecipeIds=["sprinkle-donut","iced-sprinkle-donut"];legacy.productMarkets=legacy.productMarkets.filter(x=>x.productId!=="sugar-donut");const before={balances:{...legacy.balances},finished:{...legacy.finishedProducts},contracts:[...legacy.activeContracts],transactions:[...legacy.resourceTransactions]};const migrated=normaliseBakeryState(legacy,new Date("2026-07-03T00:00:00Z"));expect(migrated.unlockedRecipeIds).toContain("sugar-donut");expect(migrated.productMarkets.find(x=>x.productId==="sugar-donut")).toMatchObject({demand:50,unlockedAt:"2026-07-03T00:00:00.000Z",lastCalculatedAt:"2026-07-03T00:00:00.000Z"});expect({balances:migrated.balances,finished:migrated.finishedProducts,contracts:migrated.activeContracts,transactions:migrated.resourceTransactions}).toEqual(before);expect(normaliseBakeryState(migrated,new Date("2026-07-04T00:00:00Z"))).toEqual(migrated)});
});
