import { describe, expect, it } from "vitest";
import { createInitialBakeryState, migrateAppData, SaleContract } from "../../domain";
import { PRODUCT_MARKETS, advanceProductMarket, applyCompletedSale, createProductMarket, deriveEffectiveMarketModifiers, deriveProductMarket, marketConfigFor, marketPriceForDemand, meanRevertDemand, unmetDemandTarget } from "../../domain/bakeryMarket";
import { createSeedData } from "../../seed";
import { craft, currentProductMarket, listProduct, purchaseIngredient, purchaseRecipe, removeContract, resolveDueContracts, validateBakeryConfiguration } from "./bakeryDomain";

const T0 = new Date("2026-07-01T00:00:00Z");
const hours = (value: number) => new Date(T0.getTime() + value * 3_600_000);
const funded = () => { const data = createSeedData(); data.bakery = createInitialBakeryState(T0); data.bakery.balances = { ...data.bakery.balances, coin: 200, dough: 20, sprinkles: 100, icing: 20, sugar: 20, cinnamon: 20 }; return data; };

describe("Bakery market initialisation", () => {
  it("creates only unlocked markets at neutral demand", () => { const data=createInitialBakeryState(T0); expect(data.productMarkets).toEqual([{productId:"sprinkle-donut",demand:50,unlockedAt:T0.toISOString(),lastCalculatedAt:T0.toISOString()},{productId:"sugar-donut",demand:50,unlockedAt:T0.toISOString(),lastCalculatedAt:T0.toISOString()}]); expect(data.productMarkets.some(x=>x.productId==="iced-sprinkle-donut")).toBe(false); });
  it("creates later markets atomically at purchase time", () => { let data=funded(); data=purchaseRecipe(data,"iced-sprinkle-donut","unlock",hours(2)); expect(data.bakery.productMarkets.find(x=>x.productId==="iced-sprinkle-donut")).toMatchObject({demand:50,unlockedAt:hours(2).toISOString()}); data=purchaseIngredient(data,"sugar","sugar",hours(3)); data=purchaseRecipe(data,"cinnamon-sugar-donut","unlock2",hours(4)); expect(data.bakery.productMarkets.find(x=>x.productId==="cinnamon-sugar-donut")?.demand).toBe(50); });
  it("migrates without growth, idempotently, and preserves Pass 1 contract terms", () => { const old=createInitialBakeryState(T0); const contract:SaleContract={id:"old",productId:"sprinkle-donut",askingPrice:3,marketPrice:3,listedAt:T0.toISOString(),durationMs:1000,completesAt:new Date(T0.getTime()+1000).toISOString(),completionIdempotencyKey:"old:complete",state:"active"}; const raw={...createSeedData(),bakery:{...old,schemaVersion:1,productMarkets:undefined,marketConfigVersion:undefined,displaySlots:undefined,activeContracts:[contract]}}; const once=migrateAppData(raw as never,hours(100)); expect(once.bakery.productMarkets[0].demand).toBe(50); expect(once.bakery.activeContracts[0]).toMatchObject({...contract,slotId:"display-1"}); expect(migrateAppData(once,hours(100)).bakery).toEqual(once.bakery); });
});

describe("Bakery market maths", () => {
  const config=marketConfigFor("sprinkle-donut")!;
  it("uses proportional mean reversion without overshoot",()=>{const movement=(start:number)=>Math.abs(meanRevertDemand(start,50,1,config)-start);expect(movement(0)).toBeGreaterThan(movement(40));expect(movement(40)).toBeGreaterThan(movement(49));expect(movement(100)).toBeGreaterThan(movement(60));expect(movement(60)).toBeGreaterThan(movement(51));for(const start of [-20,0,40,60,100,120])expect(meanRevertDemand(start,50,24,config)).toBeGreaterThanOrEqual(0);expect(meanRevertDemand(0,50,24,config)).toBeLessThanOrEqual(50);expect(meanRevertDemand(100,50,24,config)).toBeGreaterThanOrEqual(50);});
  it("raises unmet target by the configured exponential half-life",()=>{const market=createProductMarket("sprinkle-donut",T0);expect(unmetDemandTarget(config,market,T0)).toBe(50);expect(unmetDemandTarget(config,market,hours(96))).toBeCloseTo(59);expect(unmetDemandTarget(config,market,hours(10000))).toBeLessThanOrEqual(68);const sold=applyCompletedSale(advanceProductMarket(market,hours(12)),hours(12));expect(unmetDemandTarget(config,sold,hours(12))).toBe(50);expect(marketConfigFor("cinnamon-sugar-donut")?.unmetDemandCeiling).toBe(68);expect(marketConfigFor("jam-donut")?.unmetDemandCeiling).toBe(72);expect(marketConfigFor("mocha-donut")?.unmetDemandCeiling).toBe(78);});
  it("rounds visible whole-Coin prices with the specified multiplier",()=>{expect(marketPriceForDemand(config,50)).toBe(3);expect(marketPriceForDemand(config,0)).toBe(Math.round(3*.65));expect(marketPriceForDemand(config,100)).toBe(Math.round(3*1.35));expect([40,50,60].map(x=>marketPriceForDemand(config,x))).toEqual([3,3,3]);for(const item of PRODUCT_MARKETS)expect(marketPriceForDemand(item,0)).toBeGreaterThanOrEqual(1);});
});

describe("Bakery permanent and timed market modifiers", () => {
  const config=marketConfigFor("sprinkle-donut")!;
  it("applies Wider Audience recovery levels",()=>{const base=createProductMarket("sprinkle-donut",T0),low={...base,demand:0};for(const [level,multiplier] of [[1,1.1],[2,1.2],[3,1.35]] as const){const modifiers=deriveEffectiveMarketModifiers({purchasedUpgrades:[{upgradeId:"wider-audience",level}]});expect(modifiers.recoverySpeedMultiplier).toBe(multiplier);expect(advanceProductMarket(low,hours(24),{modifiers}).demand).toBeGreaterThan(advanceProductMarket(low,hours(24)).demand)}});
  it("applies Customer Loyalty ceilings without directly adding demand",()=>{const market=createProductMarket("sprinkle-donut",T0);for(const [level,increase] of [[1,5],[2,10],[3,15]] as const){const modifiers=deriveEffectiveMarketModifiers({purchasedUpgrades:[{upgradeId:"customer-loyalty",level}]});expect(modifiers.unmetDemandCeilingIncrease).toBe(increase);expect(unmetDemandTarget(config,market,hours(10000),{modifiers})).toBe(Math.min(100,config.unmetDemandCeiling+increase));expect(market.demand).toBe(50)}});
  it("applies Brand Resilience sale pressure levels and Spotlight suppression",()=>{const market=createProductMarket("sprinkle-donut",T0);for(const [level,multiplier] of [[1,.9],[2,.8],[3,.7]] as const){const modifiers=deriveEffectiveMarketModifiers({purchasedUpgrades:[{upgradeId:"brand-resilience",level}]});expect(modifiers.completedSaleImpactMultiplier).toBeCloseTo(multiplier);expect(applyCompletedSale(market,T0,{modifiers}).demand).toBeCloseTo(50-config.completedSaleImpact*multiplier)}expect(applyCompletedSale(market,T0,undefined,true).demand).toBe(50)});
  it("applies Premium Packaging to future visible prices only",()=>{for(const [level,multiplier] of [[1,1.03],[2,1.06],[3,1.1]] as const){const modifiers=deriveEffectiveMarketModifiers({purchasedUpgrades:[{upgradeId:"premium-packaging",level}]});expect(modifiers.productValueMultiplier).toBeCloseTo(multiplier);expect(marketPriceForDemand(config,50,modifiers)).toBe(Math.max(1,Math.round(config.neutralPrice*multiplier)))}});
  it("splits offline market movement at timed campaign boundaries",()=>{const market={...createProductMarket("sprinkle-donut",T0),demand:0};const always=advanceProductMarket(market,hours(48),{timedCampaigns:[{campaignId:"bakery-promotion",targetProductId:null,startsAt:T0.toISOString(),endsAt:hours(48).toISOString(),operationId:"x"} as never]});const partial=advanceProductMarket(market,hours(48),{timedCampaigns:[{campaignId:"bakery-promotion",targetProductId:null,startsAt:hours(24).toISOString(),endsAt:hours(36).toISOString(),operationId:"x"} as never]});const none=advanceProductMarket(market,hours(48));expect(partial.demand).toBeGreaterThan(none.demand);expect(partial.demand).toBeLessThan(always.demand);const windowed=deriveProductMarket(createProductMarket("sprinkle-donut",T0),hours(48),{timedCampaigns:[{campaignId:"window-promotion",targetProductId:"sprinkle-donut",startsAt:hours(12).toISOString(),endsAt:hours(36).toISOString(),operationId:"w"} as never]});expect(windowed.targetDemand).toBeGreaterThan(deriveProductMarket(createProductMarket("sprinkle-donut",T0),hours(48)).targetDemand)});
});

describe("Bakery sale pressure and locked terms",()=>{
  it("applies configured pressure only on completion",()=>{for(const [id,impact] of [["sprinkle-donut",8],["cinnamon-sugar-donut",8],["jam-donut",7],["mocha-donut",6]] as const){const market=createProductMarket(id,T0);expect(applyCompletedSale(market,T0).demand).toBe(50-impact);}let data=funded();const before=data.bakery.productMarkets[0].demand;data=craft(data,"sprinkle-donut",1,"craft",T0);data=listProduct(data,"sprinkle-donut",3,T0,"list");expect(data.bakery.productMarkets[0].demand).toBe(before);data=removeContract(data,data.bakery.activeContracts[0].id,"remove",T0);expect(data.bakery.productMarkets[0].demand).toBe(before);});
  it("locks market price, demand, completion, and awards exactly once",()=>{let data=funded();data.bakery.finishedProducts["sprinkle-donut"]=1;const listed=listProduct(data,"sprinkle-donut",3,T0,"list");const locked={...listed.bakery.activeContracts[0]};expect(locked).toMatchObject({marketPrice:3,demandAtListing:50,completesAt:hours(8).toISOString()});listed.bakery.productMarkets[0].demand=0;const sold=resolveDueContracts(listed,hours(8),"resolve");expect(sold.bakery.balances.coin).toBe(205);expect(resolveDueContracts(sold,hours(9),"again").bakery.balances.coin).toBe(205);expect(locked.askingPrice).toBe(3);});
  it("relisting uses freshly derived market conditions",()=>{let data=funded();data.bakery.finishedProducts["iced-sprinkle-donut"]=1;data=purchaseRecipe(data,"iced-sprinkle-donut","unlock",T0);let listed=listProduct(data,"iced-sprinkle-donut",8,T0,"one");const id=listed.bakery.activeContracts[0].id;listed=removeContract(listed,id,"remove",hours(1));listed.bakery.productMarkets.find(x=>x.productId==="iced-sprinkle-donut")!.demand=0;const relisted=listProduct(listed,"iced-sprinkle-donut",1,hours(2),"two");expect(relisted.bakery.activeContracts[0].marketPrice).toBeLessThan(8);});
});

describe("Bakery offline chronology and validation",()=>{
  it("resolves due contracts by timestamp then ID and leaves unfinished contracts",()=>{let data=funded();data.bakery.finishedProducts["sprinkle-donut"]=3;const make=(id:string,complete:number):SaleContract=>({id,productId:"sprinkle-donut",askingPrice:1,marketPrice:3,demandAtListing:50,listedAt:T0.toISOString(),durationMs:complete*3600000,completesAt:hours(complete).toISOString(),completionIdempotencyKey:`${id}:complete`,state:"active"});data.bakery.activeContracts=[make("b",2),make("a",2),make("later",20)];const sold=resolveDueContracts(data,hours(10),"offline");expect(sold.bakery.resourceTransactions.filter(x=>x.type==="sale-completed").map(x=>x.source)).toEqual(["a","b"]);expect(sold.bakery.activeContracts.map(x=>x.id)).toEqual(["later"]);expect(sold.bakery.balances.coin).toBe(204);expect(sold.bakery.productMarkets[0].lastSaleAt).toBe(hours(2).toISOString());});
  it("validates canonical market structure safely",()=>{const data=funded();expect(validateBakeryConfiguration(data.bakery,T0).valid).toBe(true);data.bakery.productMarkets=[];expect(validateBakeryConfiguration(data.bakery,T0).errors.join(" ")).toContain("missing market state");});
  it("derives read-only current state without mutating persisted state",()=>{const data=funded();const before=structuredClone(data.bakery.productMarkets[0]);expect(currentProductMarket(data,"sprinkle-donut",hours(96)).state.demand).toBeGreaterThan(50);expect(data.bakery.productMarkets[0]).toEqual(before);});
});
