import {describe,expect,it} from "vitest";
import {createSeedData} from "../../seed";
import {migrateAppData} from "../../domain";
import {advertisingCost,fillAvailableSlots,listWithStrategy,purchaseCampaign,purchaseCampaignWithProgress,purchaseUpgrade,purchaseUpgradeWithProgress,queueProduct,removeQueueEntry,strategyPrice} from "./bakeryBusinessDomain";
import {ingredientPackQuote,purchaseIngredient,resolveDueContracts} from "./bakeryDomain";
const at=new Date("2026-07-01T00:00:00Z");
const funded=()=>{const d=createSeedData();d.bakery.balances.coin=10000;d.bakery.finishedProducts["sprinkle-donut"]=10;return d};
describe("Bakery business expansion",()=>{
	 it("migrates to four stable slots without changing an existing contract",()=>{const d=funded(),before={id:"legacy",productId:"sprinkle-donut",askingPrice:3,marketPrice:3,listedAt:at.toISOString(),durationMs:1000,completesAt:new Date(at.getTime()+1000).toISOString(),completionIdempotencyKey:"legacy:complete",state:"active" as const};d.bakery.activeContracts=[before];const m=migrateAppData({...d,bakery:{...d.bakery,schemaVersion:3,displaySlots:undefined as never}},at);expect(m.bakery.schemaVersion).toBe(6);expect(m.bakery.displaySlots.map(x=>x.id)).toEqual(["display-1","display-2","display-3","display-4"]);expect(m.bakery.activeContracts[0]).toMatchObject({...before,slotId:"display-1"});expect(migrateAppData(m,at).bakery).toEqual(m.bakery)});
 it("enforces slot costs, order, and idempotent operation IDs",()=>{let d=funded();expect(()=>purchaseUpgrade(d,"display-slot-3","bad",at)).toThrow(/prerequisite/i);d=purchaseUpgrade(d,"display-slot-2","slot2",at);expect(d.bakery.balances.coin).toBe(9940);expect(d.bakery.displaySlots[1].unlocked).toBe(true);expect(purchaseUpgrade(d,"display-slot-2","slot2",at)).toEqual(d)});
 it("uses deterministic Quick, Market and Premium strategies",()=>{expect(strategyPrice(3,"quick")).toBe(1);expect(strategyPrice(3,"market")).toBe(3);expect(strategyPrice(3,"premium")).toBe(5)});
 it("reserves queue inventory, returns removals, and prices only on activation",()=>{let d=funded();d=purchaseUpgrade(d,"display-slot-2","s",at);d=purchaseUpgrade(d,"contract-queue-1","q",at);d=listWithStrategy(d,"sprinkle-donut","market","list",at);d=queueProduct(d,"sprinkle-donut","premium","queue",at);expect(d.bakery.finishedProducts["sprinkle-donut"]).toBe(8);expect(d.bakery.displayQueue[0]).not.toHaveProperty("askingPrice");const removed=removeQueueEntry(d,d.bakery.displayQueue[0].id,"remove",at);expect(removed.bakery.finishedProducts["sprinkle-donut"]).toBe(9);d=queueProduct(removed,"sprinkle-donut","premium","queue2",at);d.bakery.activeContracts=[];const filled=fillAvailableSlots(d.bakery,at,"fill");expect(filled.activeContracts[0]).toMatchObject({slotId:"display-1",askingPrice:5})});
 it("applies advertising discounts and leaves locked contracts unchanged",()=>{let d=funded();d.bakery.finishedProducts["sprinkle-donut"]=1;d=listWithStrategy(d,"sprinkle-donut","market","list",at);const locked={...d.bakery.activeContracts[0]};d=purchaseUpgrade(d,"advertising-efficiency","eff",at);expect(advertisingCost(d.bakery,75)).toBe(68);d=purchaseCampaign(d,"local-flyers","sprinkle-donut","flyers",at);expect(d.bakery.activeContracts[0]).toEqual(locked);expect(d.bakery.productMarkets[0].demand).toBe(58)});
 it("uses progress-aware Business purchases for spending and milestones",()=>{let d=funded();d=purchaseUpgradeWithProgress(d,"display-slot-2","slot-progress",at);expect(d.bakery.statistics.lifetimeCoinSpent).toBe(60);expect(d.bakery.statistics.coinSpentOnUpgrades).toBe(60);expect(d.bakery.statistics.upgradeLevelsPurchased).toBe(1);expect(d.bakery.completedMilestones.some(x=>x.milestoneId==="second-display")).toBe(true);const afterRetry=purchaseUpgradeWithProgress(d,"display-slot-2","slot-progress",at);expect(afterRetry).toEqual(d);d=purchaseCampaignWithProgress(d,"local-flyers","sprinkle-donut","flyers-progress",at);expect(d.bakery.statistics.lifetimeCoinSpent).toBe(75);expect(d.bakery.statistics.coinSpentOnAdvertising).toBe(15);expect(d.bakery.statistics.campaignsPurchased).toBe(1)});
 it("keeps immediate campaigns on the progress-aware path",()=>{let d=funded();d.bakery.unlockedRecipeIds=["sprinkle-donut","iced-sprinkle-donut"];d.bakery.productMarkets=[...d.bakery.productMarkets,{productId:"iced-sprinkle-donut",demand:50,unlockedAt:at.toISOString(),lastCalculatedAt:at.toISOString(),lastSaleAt:new Date(at.getTime()-96*3600000).toISOString()}];for(const [campaign,target] of [["local-flyers","sprinkle-donut"],["social-campaign",null],["variety-campaign",null],["grand-reopening",null]] as const){const before=d.bakery.statistics.campaignsPurchased;d=purchaseCampaignWithProgress(d,campaign,target,`campaign-${campaign}`,at);expect(d.bakery.statistics.campaignsPurchased).toBe(before+1);expect(d.bakery.statistics.lifetimeCoinSpent).toBeGreaterThan(0)}expect(d.bakery.activeContracts).toHaveLength(0)});
 it("quotes and purchases discounted ordinary and bulk ingredient packs",()=>{let d=funded();d.bakery.unlockedSupplierIds=["common-supplier"];d=purchaseUpgrade(d,"common-ingredient-discount","discount",at);expect(ingredientPackQuote(d.bakery,"sugar","ordinary")).toMatchObject({quantity:10,price:10,discount:.05});d=purchaseUpgrade(d,"bulk-supplier-account","bulk",at);expect(ingredientPackQuote(d.bakery,"sugar","bulk")).toMatchObject({quantity:20,price:17});d=purchaseIngredient(d,"sugar","ordinary",at,"ordinary");expect(d.bakery.balances.sugar).toBe(10);expect(d.bakery.statistics.lifetimeCoinSpent).toBe(10);d=purchaseIngredient(d,"sugar","bulk-pack",at,"bulk");expect(d.bakery.balances.sugar).toBe(30);expect(d.bakery.statistics.coinSpentOnIngredients).toBe(27);expect(()=>purchaseIngredient(funded(),"sugar","bulk-denied",at,"bulk")).toThrow(/Bulk Supplier Account/i)});
 it("consumes one Product Spotlight by stable same-time sale order",()=>{let d=funded();d.bakery.finishedProducts["sprinkle-donut"]=2;d=purchaseCampaignWithProgress(d,"product-spotlight","sprinkle-donut","spot",at);d.bakery.activeContracts=[{id:"b",productId:"sprinkle-donut",askingPrice:1,marketPrice:3,demandAtListing:50,listedAt:at.toISOString(),durationMs:0,completesAt:at.toISOString(),completionIdempotencyKey:"b:complete",state:"active",slotId:"display-1"},{id:"a",productId:"sprinkle-donut",askingPrice:1,marketPrice:3,demandAtListing:50,listedAt:at.toISOString(),durationMs:0,completesAt:at.toISOString(),completionIdempotencyKey:"a:complete",state:"active",slotId:"display-2"}];d=resolveDueContracts(d,at,"resolve");expect(d.bakery.productSpotlights).toHaveLength(0);expect(d.bakery.resourceTransactions.filter(x=>x.type==="spotlight-consumed").map(x=>x.source)).toEqual(["a"]);expect(d.bakery.productMarkets[0].demand).toBe(42);expect(resolveDueContracts(d,at,"resolve-again")).toEqual(d)});
});
