import { AppData, BakeryLedgerEntry, BakeryState, DomainError, SaleContract, Task, localDate, newId, normaliseBakeryState } from "../../domain";
import { PRODUCT_MARKETS, ProductMarketState, advanceProductMarket, applyCompletedSale, createProductMarket, deriveEffectiveMarketModifiers, deriveProductMarket, marketConfigFor, marketPriceForDemand } from "../../domain/bakeryMarket";
import { ALL_RESOURCE_IDS, INGREDIENTS, INGREDIENT_BY_ID, PRODUCTS as PRODUCT_LIST, PRODUCT_BY_ID, RECIPES as RECIPE_LIST, RECIPE_BY_ID, SUPPLIERS, SUPPLIER_BY_ID, discoverableRecipeIds } from "../../domain/bakeryCatalogue";
import { emptyProductSalesStatistics, evaluateMilestones, observeMarketPrices } from "../../domain/bakeryProgress";
import { ADVERTISING, ALL_UPGRADES, effectValue, ownedLevel } from "../../domain/bakeryBusiness";
import { applyDoughWindowClaim, reverseDoughWindowClaimsSafely } from "../../domain/bakeryProofing";

export const RESOURCES = ALL_RESOURCE_IDS;
export const PRODUCTS = PRODUCT_BY_ID;
export type ProductId = string;
export const RECIPES = RECIPE_BY_ID;
export type RecipeId = string;
export const SHOP = Object.fromEntries(INGREDIENTS.map((item)=>[item.id,{quantity:item.packQuantity,cost:item.packPrice,supplierId:item.supplierId}])) as Record<string,{quantity:number;cost:number;supplierId:string}>;

const entry = (operationId: string, type: string, itemId: string, amount: number, source: string, at = new Date(), idempotencyKey?: string): BakeryLedgerEntry => ({ id: newId("bakery_tx"), operationId, type, itemId, amount, source, timestamp: at.toISOString(), idempotencyKey });
const withBakery = (data: AppData, bakery: BakeryState, at = new Date()): AppData => {
  let normal=normaliseBakeryState(bakery,at); const newSales=normal.completedSaleIds.filter(id=>!data.bakery.completedSaleIds.includes(id));
  if(newSales.length){let productSales={...normal.statistics.productSales};for(const id of newSales){const contract=data.bakery.activeContracts.find(x=>x.id===id);if(!contract)continue;const old=productSales[contract.productId]??emptyProductSalesStatistics(),duration=Math.max(0,new Date(contract.completesAt).getTime()-new Date(contract.listedAt).getTime());productSales[contract.productId]={...old,lifetimeUnitsSold:old.lifetimeUnitsSold+1,lifetimeCoinRevenue:old.lifetimeCoinRevenue+contract.askingPrice,completedSalePriceTotal:old.completedSalePriceTotal+contract.askingPrice,marketPriceAtListingTotal:old.marketPriceAtListingTotal+contract.marketPrice,completedSaleDurationTotalMs:old.completedSaleDurationTotalMs+duration,highestCompletedSalePrice:Math.max(old.highestCompletedSalePrice??0,contract.askingPrice),fastestCompletedNonImmediateSaleMs:duration>0?Math.min(old.fastestCompletedNonImmediateSaleMs??duration,duration):old.fastestCompletedNonImmediateSaleMs,longestCompletedSaleMs:Math.max(old.longestCompletedSaleMs??0,duration),lastSaleAt:contract.completesAt,belowMarketSales:old.belowMarketSales+Number(contract.askingPrice<contract.marketPrice),atMarketSales:old.atMarketSales+Number(contract.askingPrice===contract.marketPrice),aboveMarketSales:old.aboveMarketSales+Number(contract.askingPrice>contract.marketPrice)}}normal={...normal,statistics:{...normal.statistics,completedContracts:normal.statistics.completedContracts+newSales.length,productSales}}}
  const newCrafts=normal.resourceTransactions.filter(x=>x.type==="product-created"&&!data.bakery.resourceTransactions.some(y=>y.id===x.id));if(newCrafts.length){const productSales={...normal.statistics.productSales};for(const tx of newCrafts){const old=productSales[tx.itemId]??emptyProductSalesStatistics();productSales[tx.itemId]={...old,lifetimeUnitsBaked:old.lifetimeUnitsBaked+tx.amount}}normal={...normal,statistics:{...normal.statistics,productSales}}}
  const observed=observeMarketPrices(normal,at,"market-change");return evaluateMilestones({...data,bakery:observed},observed.resourceTransactions.at(-1)?.operationId??newId("op"),at);
};
const marketFor = (bakery: BakeryState, productId: string) => bakery.productMarkets.find((market) => market.productId === productId);
const marketContext = (bakery: BakeryState) => ({ modifiers: deriveEffectiveMarketModifiers(bakery), timedCampaigns: bakery.activeCampaigns });
const spendCoin = (bakery: BakeryState, category: "ingredients" | "recipes" | "suppliers" | "advertising" | "upgrades", amount: number): BakeryState => {
  const statistics = { ...bakery.statistics, lifetimeCoinSpent: bakery.statistics.lifetimeCoinSpent + amount };
  if (category === "ingredients") statistics.coinSpentOnIngredients += amount;
  if (category === "recipes") statistics.coinSpentOnRecipes += amount;
  if (category === "suppliers") statistics.coinSpentOnSuppliers += amount;
  if (category === "advertising") statistics.coinSpentOnAdvertising += amount;
  if (category === "upgrades") statistics.coinSpentOnUpgrades += amount;
  return { ...bakery, statistics };
};
export type IngredientPackType = "ordinary" | "bulk";
export function ingredientDiscountUpgradeId(ingredientId: string) {
  const item = INGREDIENT_BY_ID[ingredientId];
  if (!item) throw new DomainError("Ingredient is unavailable.");
  if (["dough","sugar","icing","sprinkles","cinnamon","cocoa","vanilla","ginger"].includes(item.id)) return "common-ingredient-discount";
  if (["biscuit-crumb","peanut-butter","hazelnut","berries","pecan"].includes(item.id)) return "premium-ingredient-discount";
  return "filling-ingredient-discount";
}
export function ingredientPackQuote(bakery: BakeryState, ingredientId: string, packType: IngredientPackType = "ordinary") {
  const item = INGREDIENT_BY_ID[ingredientId];
  if (!item) throw new DomainError("Ingredient is unavailable.");
  const discount = effectValue(bakery.purchasedUpgrades, ingredientDiscountUpgradeId(ingredientId));
  const discountedOrdinary = item.packPrice * (1 - discount);
  const price = Math.max(1, Math.round(packType === "bulk" ? discountedOrdinary * 2 * 0.90 : discountedOrdinary));
  return { ingredientId, packType, quantity: packType === "bulk" ? item.packQuantity * 2 : item.packQuantity, price, discount };
}
export const BASIC_PACK_QUANTITY = 5;
export function supplierBasicPackQuote(bakery: BakeryState, supplierId: string) {
  const supplier = SUPPLIER_BY_ID[supplierId];
  if (!supplier) throw new DomainError("Supplier is unavailable.");
  const ingredients = supplier.ingredientIds.map((ingredientId) => ingredientPackQuote(bakery, ingredientId));
  const individualCost = ingredients.reduce((total, quote) => total + quote.price * BASIC_PACK_QUANTITY / quote.quantity, 0);
  return { supplierId, ingredientIds: [...supplier.ingredientIds], quantity: BASIC_PACK_QUANTITY, price: Math.max(1, Math.ceil(individualCost * 0.90)) };
}

export function currentProductMarket(data: AppData, productId: ProductId, now = new Date()) {
  const market = marketFor(data.bakery, productId);
  if (!market) throw new DomainError("This product market is not active.");
  return deriveProductMarket(market, now, marketContext(data.bakery));
}

export function applyTaskCompletionRewards(before: AppData, after: AppData, task: Task, operationId: string, now = new Date()): AppData {
  if (task.deletedAt || task.cancelledAt || before.statuses.find((s) => s.id === task.statusId)?.category === "cancelled") return after;
  let bakery = normaliseBakeryState(after.bakery, now); const rewards: BakeryLedgerEntry[] = []; const date = localDate(now);
  const add = (key: string, resource: string, amount: number, source: string) => { if (bakery.rewardLedger.some((x) => x.idempotencyKey === key)) return; rewards.push(entry(operationId, "productivity-reward", resource, amount, source, now, key)); bakery = { ...bakery, balances: { ...bakery.balances, [resource]: (bakery.balances[resource] ?? 0) + amount } }; };
  if (task.aggregate) add(`aggregate:${task.id}:first-completion-icing`, "icing", 2, `task:${task.id}`); else { const doughClaim=applyDoughWindowClaim(bakery,task.id,operationId,now);bakery=doughClaim.bakery;if(doughClaim.reward)rewards.push(doughClaim.reward); if(!bakery.rewardLedger.some((x)=>x.idempotencyKey===`task:${task.id}:first-completion-sprinkles`)){const amount=task.scheduledDate&&task.scheduledDate<date?1:2;add(`task:${task.id}:first-completion-sugar`,"sugar",amount,`task:${task.id}`);bakery={...bakery,statistics:{...bakery.statistics,lifetimeSugarEarned:bakery.statistics.lifetimeSugarEarned+amount}};} }
  for (const aggregate of after.tasks.filter((candidate) => candidate.aggregate && candidate.completedAt && !before.tasks.find((old) => old.id === candidate.id)?.completedAt)) add(`aggregate:${aggregate.id}:first-completion-icing`, "icing", 2, `task:${aggregate.id}`);
  return withBakery(after, { ...bakery, rewardLedger: [...bakery.rewardLedger, ...rewards] }, now);
}
export function applyProjectCompletionReward(data: AppData, projectId: string, operationId: string, now = new Date()): AppData { const key = `project:${projectId}:first-completion-icing`; if (data.bakery.rewardLedger.some((x) => x.idempotencyKey === key)) return data; const tx = entry(operationId, "productivity-reward", "icing", 5, `project:${projectId}`, now, key); return withBakery(data, { ...data.bakery, balances: { ...data.bakery.balances, icing: data.bakery.balances.icing + 5 }, rewardLedger: [...data.bakery.rewardLedger, tx] }, now); }
export function reverseRewards(data: AppData, rewardOperationId: string, operationId: string, now = new Date()): AppData { const originals = data.bakery.rewardLedger.filter((x) => x.operationId === rewardOperationId && x.type === "productivity-reward"); if (!originals.length) return data; const unreversed=originals.filter((x)=>!data.bakery.rewardLedger.some((entry)=>entry.type==="reward-reversal"&&entry.source===x.id)); if(!unreversed.length)return data; const dough=reverseDoughWindowClaimsSafely(data.bakery,unreversed,operationId,now); const balances={...dough.bakery.balances}; const otherReversals=unreversed.filter((x)=>x.itemId!=="dough").map((x)=>{if((balances[x.itemId]??0)<x.amount)throw new DomainError("The earned Bakery resources have already been used.");balances[x.itemId]-=x.amount;return entry(operationId,"reward-reversal",x.itemId,-x.amount,x.id,now,`reverse:${x.id}`)}); return withBakery(data,{...dough.bakery,balances,rewardLedger:[...data.bakery.rewardLedger,...dough.reversals,...otherReversals]},now); }
const discovered = (bakery: BakeryState) => discoverableRecipeIds(bakery.purchasedIngredientIds,bakery.unlockedSupplierIds,bakery.unlockedRecipeIds).filter((id)=>!bakery.revealedRecipeIds.includes(id));
const revealEntries = (ids:string[],operationId:string,now:Date) => ids.map((id)=>entry(operationId,"recipe-revealed",id,1,"discovery",now,`recipe-revealed:${id}`));
export function purchaseSupplier(data: AppData, supplierId: string, operationId = newId("op"), now = new Date()): AppData { const supplier=SUPPLIER_BY_ID[supplierId]; if(!supplier||supplier.id==="starting-shop") throw new DomainError("Supplier is not purchasable."); if(data.bakery.unlockedSupplierIds.includes(supplierId)) return data; if(supplier.prerequisiteSupplierId&&!data.bakery.unlockedSupplierIds.includes(supplier.prerequisiteSupplierId)) throw new DomainError("Supplier prerequisite is missing."); if(data.bakery.balances.coin<supplier.cost) throw new DomainError("Not enough Coin."); let bakery=spendCoin({...data.bakery,balances:{...data.bakery.balances,coin:data.bakery.balances.coin-supplier.cost},unlockedSupplierIds:[...data.bakery.unlockedSupplierIds,supplierId],resourceTransactions:[...data.bakery.resourceTransactions,entry(operationId,"supplier-purchased","coin",-supplier.cost,supplierId,now,`supplier:${supplierId}`)],statistics:{...data.bakery.statistics,suppliersUnlocked:data.bakery.statistics.suppliersUnlocked+1}}, "suppliers", supplier.cost); const ids=discovered(bakery); bakery={...bakery,revealedRecipeIds:[...bakery.revealedRecipeIds,...ids],resourceTransactions:[...bakery.resourceTransactions,...revealEntries(ids,operationId,now)],statistics:{...bakery.statistics,recipesRevealed:bakery.statistics.recipesRevealed+ids.length}}; return withBakery(data,bakery,now); }
export function purchaseIngredient(data: AppData, ingredient: string, operationId = newId("op"), now = new Date(), packType: IngredientPackType = "ordinary"): AppData { const definition=INGREDIENT_BY_ID[ingredient]; if(!definition) throw new DomainError("Ingredient is not available."); if(definition.supplierId!=="starting-shop"&&!data.bakery.unlockedSupplierIds.includes(definition.supplierId)) throw new DomainError("Supplier is locked."); if(packType==="bulk"&&ownedLevel(data.bakery.purchasedUpgrades,"bulk-supplier-account")<1) throw new DomainError("Bulk packs require Bulk Supplier Account."); if(data.bakery.resourceTransactions.some((tx)=>tx.idempotencyKey===`ingredient-pack:${operationId}`)) return data; const quote=ingredientPackQuote(data.bakery,ingredient,packType); if (data.bakery.balances.coin < quote.price) throw new DomainError("Not enough Coin."); let bakery=spendCoin({ ...data.bakery, balances: { ...data.bakery.balances, coin: data.bakery.balances.coin - quote.price, [ingredient]: (data.bakery.balances[ingredient]??0) + quote.quantity }, purchasedIngredientIds: [...new Set([...data.bakery.purchasedIngredientIds, ingredient])], resourceTransactions: [...data.bakery.resourceTransactions, entry(operationId, "ingredient-purchased", "coin", -quote.price, ingredient, now,`ingredient-pack:${operationId}`), entry(operationId, "ingredient-purchased", ingredient, quote.quantity, `${definition.supplierId}:${packType}`, now)],statistics:{...data.bakery.statistics,ingredientsPurchasedByType:{...data.bakery.statistics.ingredientsPurchasedByType,[ingredient]:(data.bakery.statistics.ingredientsPurchasedByType[ingredient]??0)+quote.quantity}} }, "ingredients", quote.price); const ids=discovered(bakery); bakery={...bakery,revealedRecipeIds:[...bakery.revealedRecipeIds,...ids],resourceTransactions:[...bakery.resourceTransactions,...revealEntries(ids,operationId,now)],statistics:{...bakery.statistics,recipesRevealed:bakery.statistics.recipesRevealed+ids.length}}; return withBakery(data,bakery,now); }
export function purchaseSupplierBasicPack(data: AppData, supplierId: string, operationId = newId("op"), now = new Date()): AppData {
  const supplier = SUPPLIER_BY_ID[supplierId];
  if (!supplier) throw new DomainError("Supplier is unavailable.");
  if (supplier.id !== "starting-shop" && !data.bakery.unlockedSupplierIds.includes(supplier.id)) throw new DomainError("Supplier is locked.");
  if (data.bakery.resourceTransactions.some((tx) => tx.idempotencyKey === `basic-pack:${operationId}`)) return data;
  const quote = supplierBasicPackQuote(data.bakery, supplier.id);
  if (data.bakery.balances.coin < quote.price) throw new DomainError("Not enough Coin.");
  const balances: Record<string, number> = { ...data.bakery.balances, coin: data.bakery.balances.coin - quote.price };
  const ingredientsPurchasedByType = { ...data.bakery.statistics.ingredientsPurchasedByType };
  for (const ingredientId of quote.ingredientIds) {
    balances[ingredientId] = (balances[ingredientId] ?? 0) + quote.quantity;
    ingredientsPurchasedByType[ingredientId] = (ingredientsPurchasedByType[ingredientId] ?? 0) + quote.quantity;
  }
  let bakery = spendCoin({
    ...data.bakery,
    balances,
    purchasedIngredientIds: [...new Set([...data.bakery.purchasedIngredientIds, ...quote.ingredientIds])],
    resourceTransactions: [
      ...data.bakery.resourceTransactions,
      entry(operationId, "ingredient-pack-purchased", "coin", -quote.price, supplier.id, now, `basic-pack:${operationId}`),
      ...quote.ingredientIds.map((ingredientId) => entry(operationId, "ingredient-purchased", ingredientId, quote.quantity, `${supplier.id}:basic-pack`, now)),
    ],
    statistics: { ...data.bakery.statistics, ingredientsPurchasedByType },
  }, "ingredients", quote.price);
  const ids = discovered(bakery);
  bakery = { ...bakery, revealedRecipeIds: [...bakery.revealedRecipeIds, ...ids], resourceTransactions: [...bakery.resourceTransactions, ...revealEntries(ids, operationId, now)], statistics: { ...bakery.statistics, recipesRevealed: bakery.statistics.recipesRevealed + ids.length } };
  return withBakery(data, bakery, now);
}
export function purchaseRecipe(data: AppData, recipeId: RecipeId, operationId = newId("op"), now = new Date()): AppData { const recipe = RECIPES[recipeId]; if(!recipe) throw new DomainError("Recipe is unavailable."); if (!data.bakery.revealedRecipeIds.includes(recipeId)) throw new DomainError("Recipe is not revealed."); if (data.bakery.unlockedRecipeIds.includes(recipeId)) return data; if (data.bakery.balances.coin < recipe.price) throw new DomainError("Not enough Coin."); let bakery=spendCoin({ ...data.bakery, balances: { ...data.bakery.balances, coin: data.bakery.balances.coin - recipe.price }, unlockedRecipeIds: [...data.bakery.unlockedRecipeIds, recipeId], productMarkets: [...data.bakery.productMarkets, createProductMarket(recipe.productId, now)], resourceTransactions: [...data.bakery.resourceTransactions, entry(operationId, "recipe-purchased", "coin", -recipe.price, recipeId, now,`recipe:${recipeId}`)],statistics:{...data.bakery.statistics,recipesUnlocked:data.bakery.statistics.recipesUnlocked+1} }, "recipes", recipe.price); const ids=discovered(bakery); bakery={...bakery,revealedRecipeIds:[...bakery.revealedRecipeIds,...ids],resourceTransactions:[...bakery.resourceTransactions,...revealEntries(ids,operationId,now)],statistics:{...bakery.statistics,recipesRevealed:bakery.statistics.recipesRevealed+ids.length}}; return withBakery(data,bakery,now); }
export function maxCraftable(data: AppData, recipeId: RecipeId): number { const recipe = RECIPES[recipeId]; return Math.min(...Object.entries(recipe.ingredients).map(([id, amount]) => Math.floor((data.bakery.balances[id] ?? 0) / amount))); }
export function craft(data: AppData, recipeId: RecipeId, quantity: number, operationId = newId("op"), now = new Date()): AppData { if(data.bakery.resourceTransactions.some((tx)=>tx.idempotencyKey===`craft:${operationId}`)) return data; if (!data.bakery.unlockedRecipeIds.includes(recipeId)) throw new DomainError("Recipe is not owned."); if (!Number.isInteger(quantity) || quantity < 1 || quantity > maxCraftable(data, recipeId)) throw new DomainError("Not enough ingredients."); const recipe = RECIPES[recipeId]; const balances = { ...data.bakery.balances }; const tx = [...data.bakery.resourceTransactions]; for (const [id, amount] of Object.entries(recipe.ingredients)) { balances[id] -= amount * quantity; tx.push(entry(operationId, "ingredient-consumed", id, -amount * quantity, recipeId, now)); } tx.push(entry(operationId, "product-created", recipe.productId, recipe.yield * quantity, recipeId, now,`craft:${operationId}`)); return withBakery(data, { ...data.bakery, balances, finishedProducts: { ...data.bakery.finishedProducts, [recipe.productId]: (data.bakery.finishedProducts[recipe.productId] ?? 0) + recipe.yield * quantity }, resourceTransactions: tx, statistics: { ...data.bakery.statistics, totalDonutsCrafted: data.bakery.statistics.totalDonutsCrafted + recipe.yield * quantity, bakedByProduct: { ...data.bakery.statistics.bakedByProduct, [recipe.productId]: (data.bakery.statistics.bakedByProduct[recipe.productId] ?? 0) + recipe.yield * quantity } } }, now); }
export function instantPrice(marketPrice: number) { return Math.max(1, Math.round(marketPrice / 3)); }
export function saleDurationMs(marketPrice: number, askingPrice: number) { const instant = instantPrice(marketPrice); if (askingPrice <= instant) return 0; if (marketPrice === instant) return 72 * 60 * 60 * 1000; return 8 * 60 * 60 * 1000 * ((askingPrice - instant) / (marketPrice - instant)) ** 2; }
export function maximumAskingPrice(marketPrice: number) { if (marketPrice === instantPrice(marketPrice)) return marketPrice; let price = instantPrice(marketPrice); while (8 * 60 * 60 * 1000 * ((price + 1 - instantPrice(marketPrice)) / (marketPrice - instantPrice(marketPrice))) ** 2 <= 72 * 60 * 60 * 1000) price++; return price; }
export function listProduct(data: AppData, productId: ProductId, askingPrice: number, now = new Date(), operationId = newId("op")): AppData { if (data.bakery.activeContracts.length) throw new DomainError("Display slot is occupied."); if ((data.bakery.finishedProducts[productId] ?? 0) < 1) throw new DomainError("No finished product available."); const derived = currentProductMarket(data, productId, now); const marketPrice = derived.marketPrice; if (!Number.isInteger(askingPrice) || askingPrice < 1 || askingPrice > maximumAskingPrice(marketPrice)) throw new DomainError("Choose an available whole-Coin price."); const durationMs = saleDurationMs(marketPrice, askingPrice); const id = newId("sale"); const contract: SaleContract = { id, productId, askingPrice, marketPrice, demandAtListing: derived.state.demand, listedAt: now.toISOString(), durationMs, completesAt: new Date(now.getTime() + durationMs).toISOString(), completionIdempotencyKey: `sale:${id}:complete`, state: "active" }; return withBakery(data, { ...data.bakery, productMarkets: data.bakery.productMarkets.map((market) => market.productId === productId ? derived.state : market), finishedProducts: { ...data.bakery.finishedProducts, [productId]: data.bakery.finishedProducts[productId] - 1 }, activeContracts: [contract], resourceTransactions: [...data.bakery.resourceTransactions, entry(operationId, "contract-listed", productId, -1, id, now)] }, now); }
export function removeContract(data: AppData, contractId: string, operationId = newId("op"), now = new Date()): AppData { const contract = data.bakery.activeContracts.find((x) => x.id === contractId); if (!contract) throw new DomainError("Contract is no longer active."); return withBakery(data, { ...data.bakery, activeContracts: data.bakery.activeContracts.filter((x) => x.id !== contractId), finishedProducts: { ...data.bakery.finishedProducts, [contract.productId]: (data.bakery.finishedProducts[contract.productId] ?? 0) + 1 }, resourceTransactions: [...data.bakery.resourceTransactions, entry(operationId, "contract-removed", contract.productId, 1, contract.id, now)], statistics: { ...data.bakery.statistics, removedContracts: data.bakery.statistics.removedContracts + 1,returnedProducts:data.bakery.statistics.returnedProducts+1 } }, now); }
export function resolveDueContracts(data: AppData, now = new Date(), operationId = newId("op")): AppData { let bakery = data.bakery; const due = [...bakery.activeContracts].filter((contract) => new Date(contract.completesAt).getTime() <= now.getTime()).sort((a, b) => a.completesAt.localeCompare(b.completesAt) || a.id.localeCompare(b.id)); for (const contract of due) { if (bakery.completedSaleIds.includes(contract.id) || bakery.resourceTransactions.some((tx) => tx.idempotencyKey === contract.completionIdempotencyKey)) continue; const completedAt = new Date(contract.completesAt); const market = marketFor(bakery, contract.productId); if (!market) throw new DomainError(`Missing market state for ${contract.productId}.`); const spotlight=[...bakery.productSpotlights].filter(x=>x.productId===contract.productId).sort((a,b)=>a.purchasedAt.localeCompare(b.purchasedAt)||a.id.localeCompare(b.id))[0]; const impacted = applyCompletedSale(market, completedAt, marketContext(bakery), Boolean(spotlight)); const coin = contract.askingPrice; bakery = { ...bakery, productMarkets: bakery.productMarkets.map((item) => item.productId === contract.productId ? impacted : item), balances: { ...bakery.balances, coin: bakery.balances.coin + coin }, activeContracts: bakery.activeContracts.filter((item) => item.id !== contract.id), completedSaleIds: [...bakery.completedSaleIds, contract.id], productSpotlights: spotlight?bakery.productSpotlights.filter(x=>x.id!==spotlight.id):bakery.productSpotlights, resourceTransactions: [...bakery.resourceTransactions, entry(operationId, "sale-completed", contract.productId, 1, contract.id, completedAt, contract.completionIdempotencyKey), entry(operationId, "coin-awarded", "coin", coin, contract.id, completedAt, `${contract.completionIdempotencyKey}:coin`), ...(spotlight?[entry(operationId,"spotlight-consumed",contract.productId,1,contract.id,completedAt,`spotlight:${spotlight.id}:consumed`)]:[])], statistics: { ...bakery.statistics, lifetimeCoinEarned: bakery.statistics.lifetimeCoinEarned + coin, totalDonutsSold: bakery.statistics.totalDonutsSold + 1, soldByProduct: { ...bakery.statistics.soldByProduct, [contract.productId]: (bakery.statistics.soldByProduct[contract.productId] ?? 0) + 1 }, coinByProduct: { ...bakery.statistics.coinByProduct, [contract.productId]: (bakery.statistics.coinByProduct[contract.productId] ?? 0) + coin }, highestCompletedAskingPrice: Math.max(bakery.statistics.highestCompletedAskingPrice, coin), lastCompletedSaleAt: completedAt.toISOString(), lastSaleResolutionAt: now.toISOString() } }; } if (bakery !== data.bakery) bakery = { ...bakery, productMarkets: advanceMarketsForMutation(bakery.productMarkets, now, bakery) }; return bakery === data.bakery ? data : withBakery(data, bakery, now); }

export function validateBakeryConfiguration(state?: BakeryState, now = new Date()) { const errors: string[] = []; const seen = new Set<string>(); const unitCost=(id:string)=>(INGREDIENT_BY_ID[id]?.packPrice??0)/(INGREDIENT_BY_ID[id]?.packQuantity??1); for (const recipe of RECIPE_LIST) { if (recipe.yield <= 0 || recipe.price < 0 || !(recipe.productId in PRODUCTS)) errors.push(`Invalid recipe ${recipe.id}`); for (const [id, amount] of Object.entries(recipe.ingredients)) if (!ALL_RESOURCE_IDS.includes(id as typeof ALL_RESOURCE_IDS[number]) || amount < 0) errors.push(`Invalid ingredient ${id}`); const config=marketConfigFor(recipe.productId); if (!config) errors.push(`Missing market configuration ${recipe.productId}`); else { const inputCost=Object.entries(recipe.ingredients).reduce((sum,[id,amount])=>sum+unitCost(id)*amount,0); if(config.neutralPrice<=inputCost) errors.push(`Unprofitable neutral price ${recipe.id}`); if(Math.round(config.neutralPrice*0.65)<=inputCost) errors.push(`Unprofitable weak-market price ${recipe.id}`); if(recipe.lineage){const parent=PRODUCT_BY_ID[recipe.lineage.parentRecipeId];const added=recipe.lineage.addedIngredientIds.reduce((sum,id)=>sum+unitCost(id),0);if(!parent||config.neutralPrice-parent.neutralPrice<=added) errors.push(`Invalid lineage value ${recipe.id}`);} for(const comparison of recipe.lineageComparisons??[]){const parent=PRODUCT_BY_ID[comparison.parentRecipeId];if(!parent||config.neutralPrice-parent.neutralPrice<=comparison.addedPurchasedCost) errors.push(`Invalid lineage comparison ${recipe.id}`);} } } for(const ingredient of INGREDIENTS) { if(!SUPPLIER_BY_ID[ingredient.supplierId]) errors.push(`Ingredient missing supplier ${ingredient.id}`); const useCount=RECIPE_LIST.filter((recipe)=>Object.prototype.hasOwnProperty.call(recipe.ingredients,ingredient.id)).length; if(useCount<2) errors.push(`Purchased ingredient ${ingredient.id} is used by fewer than two recipes`); } for(const supplier of SUPPLIERS) if(supplier.prerequisiteSupplierId&&!SUPPLIER_BY_ID[supplier.prerequisiteSupplierId]) errors.push(`Invalid supplier prerequisite ${supplier.id}`); for (const config of PRODUCT_MARKETS) { if (seen.has(config.productId)) errors.push(`Duplicate market configuration ${config.productId}`); seen.add(config.productId); if (config.minimumDemand >= config.maximumDemand || config.neutralDemand < config.minimumDemand || config.neutralDemand > config.maximumDemand || config.unmetDemandCeiling < config.neutralDemand || config.unmetDemandCeiling > config.maximumDemand || config.recoveryHalfLifeHours <= 0 || config.unmetDemandHalfLifeHours <= 0 || config.completedSaleImpact < 0 || config.neutralPrice <= 0 || marketPriceForDemand(config, config.minimumDemand) < 1) errors.push(`Invalid market configuration ${config.productId}`); }
  const recipeIds=new Set(RECIPE_LIST.map(recipe=>recipe.id)),ingredientIds=new Set(INGREDIENTS.map(ingredient=>ingredient.id));
  for(const recipe of RECIPE_LIST) for(const condition of [...(recipe.discovery.all??[]),...(recipe.discovery.any??[])]) { if(condition.recipeOwned&&!recipeIds.has(condition.recipeOwned)) errors.push(`Invalid recipe prerequisite ${recipe.id}`); if(condition.ingredientPurchased&&!ingredientIds.has(condition.ingredientPurchased)) errors.push(`Invalid ingredient prerequisite ${recipe.id}`); }
  const visiting=new Set<string>(),visited=new Set<string>(); const visit=(id:string):boolean=>{if(visiting.has(id))return true;if(visited.has(id))return false;visiting.add(id);for(const condition of [...(RECIPE_BY_ID[id]?.discovery.all??[]),...(RECIPE_BY_ID[id]?.discovery.any??[])])if(condition.recipeOwned&&visit(condition.recipeOwned))return true;visiting.delete(id);visited.add(id);return false;}; for(const recipe of RECIPE_LIST)if(visit(recipe.id)){errors.push(`Discovery cycle ${recipe.id}`);break;}
  if(RECIPE_LIST.some(recipe=>recipe.ingredients.dough!==1||recipe.yield!==1)) errors.push("Invalid standard Donut formula");
  if(RECIPE_BY_ID["sugar-donut"]?.price!==0||!RECIPE_BY_ID["sugar-donut"]?.discovery.visibleFromStart) errors.push("Sugar Donut starting configuration invalid");
  const handledUpgradeEffects=new Set(["rounded-price-observations","market-trend","price-history","boundary-proximity","product-statistics","display-capacity","queue-capacity","price-presets","multi-unit","dough-windows","recovery-speed","demand-ceiling","sale-impact","neutral-value","advertising-discount","bulk-pack","common-discount","filling-discount","premium-discount","sorting","low-stock","recipe-use","craftable-filter","favourites","ingredient-preview","planned-batch","multi-craft","categories"]);
  for(const upgrade of ALL_UPGRADES){if(!handledUpgradeEffects.has(upgrade.effectType)) errors.push(`Upgrade has no registered effect handler ${upgrade.id}`); for(const level of upgrade.levels) if(!Number.isFinite(level.value)||level.value<0) errors.push(`Invalid upgrade modifier ${upgrade.id}`);}
  const handledCampaignEffects=new Set(["demand-boost","spotlight","target-growth","recovery"]);
  for(const campaign of ADVERTISING){if(!handledCampaignEffects.has(campaign.effectType)) errors.push(`Campaign has no registered effect handler ${campaign.id}`); if(!Number.isFinite(campaign.effectValue)||campaign.effectValue<=0) errors.push(`Invalid campaign modifier ${campaign.id}`);}
  if(!ADVERTISING.some(x=>x.effectType==="spotlight")) errors.push("Spotlight definition missing sale resolver support");
  for(const [id,ingredients] of Object.entries({ "common-ingredient-discount":["sugar","cinnamon","cocoa","vanilla"],"filling-ingredient-discount":["chocolate","jam","custard","cream","coconut","caramel","lemon-curd","apple-filling","coffee","maple-syrup"],"premium-ingredient-discount":["biscuit-crumb","peanut-butter","hazelnut","berries"] })) if(!ingredients.every(ingredient=>INGREDIENT_BY_ID[ingredient])) errors.push(`Discount upgrade category has no mapped ingredients ${id}`);
  if(!ALL_UPGRADES.some(x=>x.id==="bulk-supplier-account")) errors.push("Bulk Supplier Account missing bulk quote support");
  if (state) { for (const market of state.productMarkets) { const config = marketConfigFor(market.productId); if (!state.unlockedRecipeIds.includes(market.productId)) errors.push(`Locked recipe has market state ${market.productId}`); if (!config || market.demand < config.minimumDemand || market.demand > config.maximumDemand) errors.push(`Invalid market state ${market.productId}`); for (const timestamp of [market.unlockedAt, market.lastCalculatedAt, market.lastSaleAt].filter(Boolean) as string[]) if (!Number.isFinite(new Date(timestamp).getTime()) || new Date(timestamp).getTime() > now.getTime() || new Date(market.lastCalculatedAt).getTime() < new Date(market.unlockedAt).getTime()) errors.push(`Invalid market timestamp ${market.productId}`); } for (const id of state.unlockedRecipeIds) if (!state.productMarkets.some((market) => market.productId === id)) errors.push(`Unlocked recipe missing market state ${id}`); }
  return { valid: errors.length === 0, errors, weakMarketProfitabilityReady: !errors.some((x)=>x.includes("weak-market")), lineageValuePreserved: !errors.some((x)=>x.includes("lineage")) };
}

export function advanceMarketsForMutation(markets: ProductMarketState[], at: Date, bakery?: BakeryState) { const context=bakery?marketContext(bakery):undefined; return markets.map((market) => advanceProductMarket(market, at, context)); }
