import { AppData,BakeryState,DisplayQueueEntry,DomainError,SaleContract,newId,normaliseBakeryState } from "../../domain";
import { INGREDIENT_BY_ID } from "../../domain/bakeryCatalogue";
import { ADVERTISING,PriceStrategy,campaignById,effectValue,ownedLevel,upgradeById } from "../../domain/bakeryBusiness";
import { deriveEffectiveMarketModifiers,deriveProductMarket,marketConfigFor } from "../../domain/bakeryMarket";
import { instantPrice,maximumAskingPrice,resolveDueContracts,saleDurationMs } from "./bakeryDomain";
import { evaluateMilestones,observeMarketPrices } from "../../domain/bakeryProgress";
import { PROOFING_SCHEDULE_UPGRADE_ID, nextSydneyLocalDate } from "../../domain/bakeryProofing";
const entry=(operationId:string,type:string,itemId:string,amount:number,source:string,at:Date,idempotencyKey?:string)=>({id:newId("bakery-tx"),operationId,type,itemId,amount,source,timestamp:at.toISOString(),idempotencyKey});
export const hasUpgrade=(bakery:BakeryState,id:string)=>ownedLevel(bakery.purchasedUpgrades,id)>0||bakery.foundationCapabilities.includes(id);
export const displayCapacity=(b:BakeryState)=>1+["display-slot-2","display-slot-3","display-slot-4"].filter(id=>hasUpgrade(b,id)).length;
export const queueCapacity=(b:BakeryState)=>["contract-queue-1","contract-queue-2"].filter(id=>hasUpgrade(b,id)).length;
const marketContext=(b:BakeryState)=>({modifiers:deriveEffectiveMarketModifiers(b),timedCampaigns:b.activeCampaigns});
export function purchaseUpgrade(data:AppData,id:string,operationId=newId("op"),now=new Date()):AppData { const d=upgradeById(id);if(!d||d.foundationProvided)throw new DomainError("Upgrade is not purchasable.");if(data.bakery.resourceTransactions.some(x=>x.idempotencyKey===`upgrade:${operationId}`))return data;const current=ownedLevel(data.bakery.purchasedUpgrades,id),next=current+1,level=d.levels[next-1];if(!level)throw new DomainError("Maximum level reached.");if(d.prerequisites.some(x=>!hasUpgrade(data.bakery,x)))throw new DomainError("Upgrade prerequisite is missing.");if(id.includes("ingredient-discount")||id==="bulk-supplier-account"){const required=id.startsWith("filling")?"filling-supplier":id.startsWith("premium")?"premium-supplier":"common-supplier";if(!data.bakery.unlockedSupplierIds.includes(required))throw new DomainError("Supplier prerequisite is missing.");}if(data.bakery.balances.coin<level.cost)throw new DomainError("Not enough Coin.");const purchasedRecord={upgradeId:id,level:next,purchasedAt:now.toISOString(),operationId,...(id===PROOFING_SCHEDULE_UPGRADE_ID?{effectiveLocalDate:nextSydneyLocalDate(now)}:{})};const purchased=[...data.bakery.purchasedUpgrades,purchasedRecord],slots=data.bakery.displaySlots.map((s,i)=>({...s,unlocked:i<displayCapacity({...data.bakery,purchasedUpgrades:purchased})}));return {...data,bakery:normaliseBakeryState({...data.bakery,balances:{...data.bakery.balances,coin:data.bakery.balances.coin-level.cost},purchasedUpgrades:purchased,displaySlots:slots,resourceTransactions:[...data.bakery.resourceTransactions,entry(operationId,"upgrade-purchased","coin",-level.cost,`${id}:${next}`,now,`upgrade:${operationId}`)]},now)}; }
export function strategyPrice(marketPrice:number,strategy:PriceStrategy){if(strategy==="quick")return instantPrice(marketPrice);if(strategy==="market")return marketPrice;let price=instantPrice(marketPrice);while(price<maximumAskingPrice(marketPrice)&&saleDurationMs(marketPrice,price+1)<=32*3600000)price++;return price;}
function contractFor(b:BakeryState,productId:string,strategy:PriceStrategy,slotId:string,at:Date):{contract:SaleContract;bakery:BakeryState}{const market=b.productMarkets.find(x=>x.productId===productId);if(!market)throw new DomainError("Product market is unavailable.");const derived=deriveProductMarket(market,at,marketContext(b)),askingPrice=strategyPrice(derived.marketPrice,strategy),id=newId("sale"),durationMs=saleDurationMs(derived.marketPrice,askingPrice);return{contract:{id,productId,askingPrice,marketPrice:derived.marketPrice,demandAtListing:derived.state.demand,listedAt:at.toISOString(),durationMs,completesAt:new Date(at.getTime()+durationMs).toISOString(),completionIdempotencyKey:`sale:${id}:complete`,state:"active",slotId},bakery:{...b,productMarkets:b.productMarkets.map(x=>x.productId===productId?derived.state:x)}}}
export function queueProduct(data:AppData,productId:string,strategy:PriceStrategy,operationId=newId("op"),now=new Date()):AppData{if(!hasUpgrade(data.bakery,"contract-queue-1")||data.bakery.displayQueue.length>=queueCapacity(data.bakery))throw new DomainError("Display queue is full or locked.");if((data.bakery.finishedProducts[productId]??0)<1)throw new DomainError("No finished product available.");if(data.bakery.resourceTransactions.some(x=>x.idempotencyKey===`queue:${operationId}`))return data;const q:DisplayQueueEntry={id:newId("queue"),productId,strategy,queuedAt:now.toISOString(),order:Math.max(0,...data.bakery.displayQueue.map(x=>x.order))+1};return{...data,bakery:normaliseBakeryState({...data.bakery,finishedProducts:{...data.bakery.finishedProducts,[productId]:data.bakery.finishedProducts[productId]-1},displayQueue:[...data.bakery.displayQueue,q],resourceTransactions:[...data.bakery.resourceTransactions,entry(operationId,"queue-entry-added",productId,-1,q.id,now,`queue:${operationId}`)]},now)}}
export function removeQueueEntry(data:AppData,id:string,operationId=newId("op"),now=new Date()):AppData{const q=data.bakery.displayQueue.find(x=>x.id===id);if(!q)throw new DomainError("Queue entry not found.");return{...data,bakery:normaliseBakeryState({...data.bakery,displayQueue:data.bakery.displayQueue.filter(x=>x.id!==id),finishedProducts:{...data.bakery.finishedProducts,[q.productId]:(data.bakery.finishedProducts[q.productId]??0)+1},resourceTransactions:[...data.bakery.resourceTransactions,entry(operationId,"queue-entry-removed",q.productId,1,q.id,now)]},now)}}
export function fillAvailableSlots(b:BakeryState,at:Date,operationId:string):BakeryState{let next=b;for(const slot of next.displaySlots.filter(x=>x.unlocked).sort((a,b)=>a.id.localeCompare(b.id))){if(next.activeContracts.some(x=>(x.slotId??"display-1")===slot.id))continue;const q=[...next.displayQueue].sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id))[0];if(!q)break;const made=contractFor(next,q.productId,q.strategy,slot.id,at);next={...made.bakery,activeContracts:[...made.bakery.activeContracts,made.contract],displayQueue:made.bakery.displayQueue.filter(x=>x.id!==q.id),resourceTransactions:[...made.bakery.resourceTransactions,entry(operationId,"queue-entry-activated",q.productId,0,made.contract.id,at)]};}return next;}
export const advertisingCost=(b:BakeryState,base:number)=>Math.max(1,Math.round(base*deriveEffectiveMarketModifiers(b).advertisingCostMultiplier));
export function purchaseCampaign(data:AppData,campaignId:string,targetProductId:string|null,operationId=newId("op"),now=new Date()):AppData{const d=campaignById(campaignId);if(!d)throw new DomainError("Campaign is unavailable.");if(data.bakery.resourceTransactions.some(x=>x.idempotencyKey===`campaign:${operationId}`))return data;const unlocked=data.bakery.unlockedRecipeIds,targets=d.targetType==="product"?(targetProductId&&unlocked.includes(targetProductId)?[targetProductId]:[]):d.targetType==="neglected-products"?unlocked.filter(id=>{const t=data.bakery.productMarkets.find(x=>x.productId===id)?.lastSaleAt;return !t||now.getTime()-new Date(t).getTime()>=72*3600000}):unlocked;if(!targets.length)throw new DomainError("No eligible campaign targets.");if(d.durationMs&&data.bakery.activeCampaigns.some(x=>x.campaignId===campaignId&&x.targetProductId===(d.targetType==="product"?targetProductId:null)&&new Date(x.endsAt)>now))throw new DomainError("This campaign is already active.");if(campaignId==="product-spotlight"&&data.bakery.productSpotlights.some(x=>x.productId===targetProductId))throw new DomainError("A Spotlight is already pending.");const cost=advertisingCost(data.bakery,d.baseCost);if(data.bakery.balances.coin<cost)throw new DomainError("Not enough Coin.");let b={...data.bakery,balances:{...data.bakery.balances,coin:data.bakery.balances.coin-cost},resourceTransactions:[...data.bakery.resourceTransactions,entry(operationId,"campaign-purchased","coin",-cost,campaignId,now,`campaign:${operationId}`)]};if(d.effectType==="demand-boost")b={...b,productMarkets:b.productMarkets.map(m=>targets.includes(m.productId)?{...m,demand:Math.min(marketConfigFor(m.productId)?.maximumDemand??100,m.demand+d.effectValue),lastCalculatedAt:now.toISOString()}:m)};else if(d.effectType==="spotlight")b={...b,productSpotlights:[...b.productSpotlights,{id:newId("spotlight"),productId:targets[0],purchasedAt:now.toISOString(),operationId}]};else b={...b,activeCampaigns:[...b.activeCampaigns,{id:newId("campaign"),campaignId,targetProductId:d.targetType==="product"?targets[0]:null,startsAt:now.toISOString(),endsAt:new Date(now.getTime()+d.durationMs!).toISOString(),operationId}]};return{...data,bakery:normaliseBakeryState(b,now)}}
export function ingredientPackPrice(b:BakeryState,id:string,bulk=false){const item=INGREDIENT_BY_ID[id];if(!item)throw new DomainError("Ingredient is unavailable.");const upgrade=item.supplierId==="common-supplier"?"common-ingredient-discount":item.supplierId==="filling-supplier"?"filling-ingredient-discount":"premium-ingredient-discount",discount=effectValue(b.purchasedUpgrades,upgrade),base=item.packPrice*(1-discount);return Math.max(1,Math.round(bulk?base*2*.9:base));}
export { ADVERTISING };
export function listCustomInSlot(data:AppData,productId:string,askingPrice:number,operationId=newId("op"),now=new Date()):AppData{const slot=data.bakery.displaySlots.filter(x=>x.unlocked&&!data.bakery.activeContracts.some(c=>(c.slotId??"display-1")===x.id)).sort((a,b)=>a.id.localeCompare(b.id))[0];if(!slot)throw new DomainError("All Display slots are occupied.");if((data.bakery.finishedProducts[productId]??0)<1)throw new DomainError("No finished product available.");const market=data.bakery.productMarkets.find(x=>x.productId===productId);if(!market)throw new DomainError("Product market unavailable.");const derived=deriveProductMarket(market,now,marketContext(data.bakery));if(!Number.isInteger(askingPrice)||askingPrice<1||askingPrice>maximumAskingPrice(derived.marketPrice))throw new DomainError("Choose an available whole-Coin price.");const id=newId("sale"),durationMs=saleDurationMs(derived.marketPrice,askingPrice),contract:SaleContract={id,productId,askingPrice,marketPrice:derived.marketPrice,demandAtListing:derived.state.demand,listedAt:now.toISOString(),durationMs,completesAt:new Date(now.getTime()+durationMs).toISOString(),completionIdempotencyKey:`sale:${id}:complete`,state:"active",slotId:slot.id};return{...data,bakery:normaliseBakeryState({...data.bakery,productMarkets:data.bakery.productMarkets.map(x=>x.productId===productId?derived.state:x),activeContracts:[...data.bakery.activeContracts,contract],finishedProducts:{...data.bakery.finishedProducts,[productId]:data.bakery.finishedProducts[productId]-1},resourceTransactions:[...data.bakery.resourceTransactions,entry(operationId,"contract-listed",productId,-1,id,now)]},now)}}
export function listWithStrategy(data:AppData,productId:string,strategy:PriceStrategy,operationId=newId("op"),now=new Date()):AppData{const slot=data.bakery.displaySlots.filter(x=>x.unlocked&&!data.bakery.activeContracts.some(c=>(c.slotId??"display-1")===x.id)).sort((a,b)=>a.id.localeCompare(b.id))[0];if(!slot)throw new DomainError("All Display slots are occupied.");if((data.bakery.finishedProducts[productId]??0)<1)throw new DomainError("No finished product available.");const made=contractFor(data.bakery,productId,strategy,slot.id,now);return{...data,bakery:normaliseBakeryState({...made.bakery,activeContracts:[...made.bakery.activeContracts,made.contract],finishedProducts:{...made.bakery.finishedProducts,[productId]:made.bakery.finishedProducts[productId]-1},savedPriceStrategies:{...made.bakery.savedPriceStrategies,[productId]:strategy},resourceTransactions:[...made.bakery.resourceTransactions,entry(operationId,"contract-listed",productId,-1,made.contract.id,now)]},now)}}
export function resolveBakeryTimeline(data:AppData,now=new Date(),operationId=newId("op")):AppData{let next=data,guard=0;while(guard++<1000){const earliest=[...next.bakery.activeContracts].filter(c=>new Date(c.completesAt)<=now).sort((a,b)=>a.completesAt.localeCompare(b.completesAt)||a.id.localeCompare(b.id))[0];if(!earliest)break;const at=new Date(earliest.completesAt),resolved=resolveDueContracts(next,at,operationId),filled=fillAvailableSlots(resolved.bakery,at,operationId);next={...resolved,bakery:normaliseBakeryState(filled,at)};}const activeCampaigns=next.bakery.activeCampaigns.filter(x=>new Date(x.endsAt)>now);if(activeCampaigns.length!==next.bakery.activeCampaigns.length)next={...next,bakery:normaliseBakeryState({...next.bakery,activeCampaigns},now)};return next}

export function purchaseUpgradeWithProgress(data:AppData,id:string,operationId=newId("op"),now=new Date()){const next=purchaseUpgrade(data,id,operationId,now);if(next===data)return data;const definition=upgradeById(id),level=ownedLevel(next.bakery.purchasedUpgrades,id),cost=definition?.levels[level-1]?.cost??0;let bakery={...next.bakery,statistics:{...next.bakery.statistics,lifetimeCoinSpent:next.bakery.statistics.lifetimeCoinSpent+cost,coinSpentOnUpgrades:next.bakery.statistics.coinSpentOnUpgrades+cost,upgradeLevelsPurchased:next.bakery.statistics.upgradeLevelsPurchased+1}};bakery=observeMarketPrices(bakery,now,id==="price-ledger"?"ledger-start":"upgrade");return evaluateMilestones({...next,bakery},operationId,now)}
export function purchaseCampaignWithProgress(data:AppData,campaignId:string,targetProductId:string|null,operationId=newId("op"),now=new Date()){const next=purchaseCampaign(data,campaignId,targetProductId,operationId,now);if(next===data)return data;const cost=advertisingCost(data.bakery,campaignById(campaignId)?.baseCost??0),bakery=observeMarketPrices({...next.bakery,statistics:{...next.bakery.statistics,lifetimeCoinSpent:next.bakery.statistics.lifetimeCoinSpent+cost,coinSpentOnAdvertising:next.bakery.statistics.coinSpentOnAdvertising+cost,campaignsPurchased:next.bakery.statistics.campaignsPurchased+1}},now,"campaign");return evaluateMilestones({...next,bakery},operationId,now)}
